DROP TABLE IF EXISTS event_occurrences;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS event_series;
DROP TABLE IF EXISTS places;
DROP TABLE IF EXISTS organizations;

DROP EXTENSION IF EXISTS postgis;
DROP EXTENSION IF EXISTS pg_trgm;
DROP EXTENSION IF EXISTS pgcrypto;