// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users
SET is_active = true
WHERE id = $1
`

func (q *Queries) ActivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateUser, id)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE 
  ($1::boolean IS NULL OR is_active = $1) AND
  ($2::text IS NULL OR role = $2) AND
  deleted_at IS NULL
`

type CountUsersParams struct {
	IsActive pgtype.Bool `json:"is_active"`
	Role     pgtype.Text `json:"role"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.IsActive, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (prefix, key_hash, hash_version, name, source_id, role, rate_limit_tier, is_active, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, prefix, name, role, rate_limit_tier, is_active, created_at, expires_at
`

type CreateAPIKeyParams struct {
	Prefix        string             `json:"prefix"`
	KeyHash       string             `json:"key_hash"`
	HashVersion   int32              `json:"hash_version"`
	Name          string             `json:"name"`
	SourceID      pgtype.UUID        `json:"source_id"`
	Role          string             `json:"role"`
	RateLimitTier string             `json:"rate_limit_tier"`
	IsActive      bool               `json:"is_active"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type CreateAPIKeyRow struct {
	ID            pgtype.UUID        `json:"id"`
	Prefix        string             `json:"prefix"`
	Name          string             `json:"name"`
	Role          string             `json:"role"`
	RateLimitTier string             `json:"rate_limit_tier"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Prefix,
		arg.KeyHash,
		arg.HashVersion,
		arg.Name,
		arg.SourceID,
		arg.Role,
		arg.RateLimitTier,
		arg.IsActive,
		arg.ExpiresAt,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Prefix,
		&i.Name,
		&i.Role,
		&i.RateLimitTier,
		&i.IsActive,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, role, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, role, is_active, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	IsActive     bool   `json:"is_active"`
}

type CreateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.IsActive,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createUserInvitation = `-- name: CreateUserInvitation :one

INSERT INTO user_invitations (user_id, token_hash, email, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token_hash, email, expires_at, created_at
`

type CreateUserInvitationParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
}

type CreateUserInvitationRow struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// User Invitation Queries
func (q *Queries) CreateUserInvitation(ctx context.Context, arg CreateUserInvitationParams) (CreateUserInvitationRow, error) {
	row := q.db.QueryRow(ctx, createUserInvitation,
		arg.UserID,
		arg.TokenHash,
		arg.Email,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i CreateUserInvitationRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAPIKey = `-- name: DeactivateAPIKey :exec
UPDATE api_keys
SET is_active = false
WHERE id = $1
`

func (q *Queries) DeactivateAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAPIKey, id)
	return err
}

const deactivateUser = `-- name: DeactivateUser :exec

UPDATE users
SET is_active = false
WHERE id = $1
`

// User Management Queries
func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, prefix, key_hash, hash_version, name, source_id, role, rate_limit_tier, is_active, last_used_at, expires_at
FROM api_keys
WHERE prefix = $1 AND is_active = true
LIMIT 1
`

type GetAPIKeyByPrefixRow struct {
	ID            pgtype.UUID        `json:"id"`
	Prefix        string             `json:"prefix"`
	KeyHash       string             `json:"key_hash"`
	HashVersion   int32              `json:"hash_version"`
	Name          string             `json:"name"`
	SourceID      pgtype.UUID        `json:"source_id"`
	Role          string             `json:"role"`
	RateLimitTier string             `json:"rate_limit_tier"`
	IsActive      bool               `json:"is_active"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i GetAPIKeyByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.Prefix,
		&i.KeyHash,
		&i.HashVersion,
		&i.Name,
		&i.SourceID,
		&i.Role,
		&i.RateLimitTier,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, username, email, password_hash, role, is_active, created_at, last_login_at
FROM users
WHERE email = $1 AND is_active = true
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

// SQLc queries for authentication.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, role, is_active, created_at, last_login_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, role, is_active, created_at, last_login_at
FROM users
WHERE username = $1 AND is_active = true
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserInvitationByTokenHash = `-- name: GetUserInvitationByTokenHash :one
SELECT id, user_id, token_hash, email, expires_at, accepted_at, created_by, created_at
FROM user_invitations
WHERE token_hash = $1 AND expires_at > now() AND accepted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserInvitationByTokenHash(ctx context.Context, tokenHash string) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, getUserInvitationByTokenHash, tokenHash)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Email,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, prefix, name, source_id, role, rate_limit_tier, is_active, created_at, last_used_at, expires_at
FROM api_keys
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID            pgtype.UUID        `json:"id"`
	Prefix        string             `json:"prefix"`
	Name          string             `json:"name"`
	SourceID      pgtype.UUID        `json:"source_id"`
	Role          string             `json:"role"`
	RateLimitTier string             `json:"rate_limit_tier"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Prefix,
			&i.Name,
			&i.SourceID,
			&i.Role,
			&i.RateLimitTier,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsForUser = `-- name: ListPendingInvitationsForUser :many
SELECT id, token_hash, email, expires_at, created_at
FROM user_invitations
WHERE user_id = $1 AND accepted_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

type ListPendingInvitationsForUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	TokenHash string             `json:"token_hash"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingInvitationsForUser(ctx context.Context, userID pgtype.UUID) ([]ListPendingInvitationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsForUserRow{}
	for rows.Next() {
		var i ListPendingInvitationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.Email,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, role, is_active, created_at, last_login_at
FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithFilters = `-- name: ListUsersWithFilters :many
SELECT id, username, email, role, is_active, created_at, last_login_at
FROM users
WHERE 
  ($1::boolean IS NULL OR is_active = $1) AND
  ($2::text IS NULL OR role = $2) AND
  deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListUsersWithFiltersParams struct {
	IsActive pgtype.Bool `json:"is_active"`
	Role     pgtype.Text `json:"role"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

type ListUsersWithFiltersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) ListUsersWithFilters(ctx context.Context, arg ListUsersWithFiltersParams) ([]ListUsersWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithFilters,
		arg.IsActive,
		arg.Role,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithFiltersRow{}
	for rows.Next() {
		var i ListUsersWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE user_invitations
SET accepted_at = now()
WHERE id = $1
`

func (q *Queries) MarkInvitationAccepted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, id)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = now()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = $2,
    email = $3,
    role = $4,
    is_active = $5
WHERE id = $1
`

type UpdateUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
	Role     string      `json:"role"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.IsActive,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
