// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBatchIngestionResult = `-- name: CreateBatchIngestionResult :exec
INSERT INTO batch_ingestion_results (batch_id, results, completed_at)
VALUES ($1, $2, $3)
ON CONFLICT (batch_id) DO UPDATE
SET results = EXCLUDED.results, completed_at = EXCLUDED.completed_at
`

type CreateBatchIngestionResultParams struct {
	BatchID     string             `json:"batch_id"`
	Results     []byte             `json:"results"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateBatchIngestionResult(ctx context.Context, arg CreateBatchIngestionResultParams) error {
	_, err := q.db.Exec(ctx, createBatchIngestionResult, arg.BatchID, arg.Results, arg.CompletedAt)
	return err
}

const getBatchIngestionResult = `-- name: GetBatchIngestionResult :one

SELECT batch_id, results, completed_at, created_at
FROM batch_ingestion_results
WHERE batch_id = $1
`

// SQLc queries for batch ingestion operations.
func (q *Queries) GetBatchIngestionResult(ctx context.Context, batchID string) (BatchIngestionResult, error) {
	row := q.db.QueryRow(ctx, getBatchIngestionResult, batchID)
	var i BatchIngestionResult
	err := row.Scan(
		&i.BatchID,
		&i.Results,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
