// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_review_queue.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveReview = `-- name: ApproveReview :one
UPDATE event_review_queue
   SET status = 'approved',
       reviewed_by = $1,
       reviewed_at = NOW(),
       review_notes = $2,
       updated_at = NOW()
 WHERE id = $3
   AND status = 'pending'
RETURNING id, event_id, original_payload, normalized_payload, warnings, source_id, source_external_id, dedup_hash, event_start_time, event_end_time, status, reviewed_by, reviewed_at, review_notes, rejection_reason, created_at, updated_at, duplicate_of_event_id
`

type ApproveReviewParams struct {
	ReviewedBy pgtype.Text `json:"reviewed_by"`
	Notes      pgtype.Text `json:"notes"`
	ID         int32       `json:"id"`
}

// Mark review as approved
func (q *Queries) ApproveReview(ctx context.Context, arg ApproveReviewParams) (EventReviewQueue, error) {
	row := q.db.QueryRow(ctx, approveReview, arg.ReviewedBy, arg.Notes, arg.ID)
	var i EventReviewQueue
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OriginalPayload,
		&i.NormalizedPayload,
		&i.Warnings,
		&i.SourceID,
		&i.SourceExternalID,
		&i.DedupHash,
		&i.EventStartTime,
		&i.EventEndTime,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DuplicateOfEventID,
	)
	return i, err
}

const cleanupArchivedReviews = `-- name: CleanupArchivedReviews :exec
DELETE FROM event_review_queue
 WHERE status IN ('approved', 'superseded', 'merged', 'dismissed')
   AND reviewed_at < NOW() - INTERVAL '90 days'
`

// Archive old approved/superseded/merged/dismissed reviews (90 day retention)
func (q *Queries) CleanupArchivedReviews(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupArchivedReviews)
	return err
}

const cleanupExpiredRejections = `-- name: CleanupExpiredRejections :exec
DELETE FROM event_review_queue
 WHERE status = 'rejected'
   AND (
     event_end_time < NOW() - INTERVAL '7 days'
     OR (event_end_time IS NULL AND event_start_time < NOW() - INTERVAL '7 days')
   )
`

// Delete rejected reviews for past events (7 day grace period)
func (q *Queries) CleanupExpiredRejections(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredRejections)
	return err
}

const cleanupUnreviewedEvents = `-- name: CleanupUnreviewedEvents :exec
DELETE FROM event_review_queue
 WHERE status = 'pending'
   AND event_start_time < NOW()
`

// Delete pending reviews for events that have already started (too late to review)
func (q *Queries) CleanupUnreviewedEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupUnreviewedEvents)
	return err
}

const countReviewQueueByStatus = `-- name: CountReviewQueueByStatus :one
SELECT COUNT(*) as total
  FROM event_review_queue
 WHERE ($1::text IS NULL OR status = $1)
`

// Count total reviews by status (for badge display)
func (q *Queries) CountReviewQueueByStatus(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewQueueByStatus, status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createReviewQueueEntry = `-- name: CreateReviewQueueEntry :one
INSERT INTO event_review_queue (
  event_id,
  original_payload,
  normalized_payload,
  warnings,
  source_id,
  source_external_id,
  dedup_hash,
  event_start_time,
  event_end_time,
  duplicate_of_event_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
RETURNING id, event_id, original_payload, normalized_payload, warnings, source_id, source_external_id, dedup_hash, event_start_time, event_end_time, status, reviewed_by, reviewed_at, review_notes, rejection_reason, created_at, updated_at, duplicate_of_event_id
`

type CreateReviewQueueEntryParams struct {
	EventID            pgtype.UUID        `json:"event_id"`
	OriginalPayload    []byte             `json:"original_payload"`
	NormalizedPayload  []byte             `json:"normalized_payload"`
	Warnings           []byte             `json:"warnings"`
	SourceID           pgtype.Text        `json:"source_id"`
	SourceExternalID   pgtype.Text        `json:"source_external_id"`
	DedupHash          pgtype.Text        `json:"dedup_hash"`
	EventStartTime     pgtype.Timestamptz `json:"event_start_time"`
	EventEndTime       pgtype.Timestamptz `json:"event_end_time"`
	DuplicateOfEventID pgtype.UUID        `json:"duplicate_of_event_id"`
}

// Create new review queue entry
func (q *Queries) CreateReviewQueueEntry(ctx context.Context, arg CreateReviewQueueEntryParams) (EventReviewQueue, error) {
	row := q.db.QueryRow(ctx, createReviewQueueEntry,
		arg.EventID,
		arg.OriginalPayload,
		arg.NormalizedPayload,
		arg.Warnings,
		arg.SourceID,
		arg.SourceExternalID,
		arg.DedupHash,
		arg.EventStartTime,
		arg.EventEndTime,
		arg.DuplicateOfEventID,
	)
	var i EventReviewQueue
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OriginalPayload,
		&i.NormalizedPayload,
		&i.Warnings,
		&i.SourceID,
		&i.SourceExternalID,
		&i.DedupHash,
		&i.EventStartTime,
		&i.EventEndTime,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DuplicateOfEventID,
	)
	return i, err
}

const dismissAllCompanionWarnings = `-- name: DismissAllCompanionWarnings :one
WITH target_event AS (
  SELECT id FROM events WHERE ulid = $2 LIMIT 1
),
stripped AS (
  SELECT COALESCE(jsonb_agg(new_w ORDER BY idx), '[]'::jsonb) AS warnings
  FROM (
    SELECT idx,
           CASE
             WHEN w->>'code' = 'potential_duplicate' THEN (
               SELECT CASE WHEN jsonb_array_length(rebuilt) = 0 THEN NULL
                           ELSE jsonb_set(w, '{details,matches}', rebuilt)
                      END
               FROM (
                 SELECT COALESCE(jsonb_agg(m), '[]'::jsonb) AS rebuilt
                 FROM jsonb_array_elements(w->'details'->'matches') m
                 WHERE m->>'ulid' <> $2::text
               ) _
             )
             WHEN w->>'code' = 'cross_week_series_companion'
                  AND w->'details'->>'companion_ulid' = $2::text THEN NULL
             ELSE w
           END AS new_w
    FROM event_review_queue rq,
         jsonb_array_elements(rq.warnings) WITH ORDINALITY AS t(w, idx)
    WHERE rq.id = $1::int
      AND NOT (
        w->>'code' = 'near_duplicate_of_new_event'
        AND rq.duplicate_of_event_id = (SELECT id FROM target_event)
      )
  ) sub
  WHERE new_w IS NOT NULL
)
UPDATE event_review_queue
   SET warnings = stripped.warnings,
       duplicate_of_event_id = CASE
         WHEN duplicate_of_event_id = (SELECT id FROM target_event) THEN NULL
         ELSE duplicate_of_event_id
       END,
       updated_at = NOW()
  FROM stripped
 WHERE id = $1::int
   AND status = 'pending'
RETURNING (stripped.warnings = '[]'::jsonb) AS warnings_empty
`

type DismissAllCompanionWarningsParams struct {
	ReviewID  int32  `json:"review_id"`
	EventUlid string `json:"event_ulid"`
}

// Atomically strips all companion warning entries referencing the given event_ulid
// from a specific review row. Handles three warning types:
//
//	near_duplicate_of_new_event  — stripped when duplicate_of_event_id matches
//	potential_duplicate          — specific match entries filtered; warning nullified when matches empty
//	cross_week_series_companion  — stripped when details->>'companion_ulid' matches
//
// Also clears duplicate_of_event_id if it points to the given event.
// Returns true (warnings_empty) when the resulting warnings array is empty after stripping.
func (q *Queries) DismissAllCompanionWarnings(ctx context.Context, arg DismissAllCompanionWarningsParams) (bool, error) {
	row := q.db.QueryRow(ctx, dismissAllCompanionWarnings, arg.ReviewID, arg.EventUlid)
	var warnings_empty bool
	err := row.Scan(&warnings_empty)
	return warnings_empty, err
}

const dismissCompanionWarningMatch = `-- name: DismissCompanionWarningMatch :exec
UPDATE event_review_queue
   SET warnings = (
         SELECT COALESCE(jsonb_agg(new_w ORDER BY idx), '[]'::jsonb)
         FROM (
           SELECT idx,
                  CASE
                    WHEN w->>'code' = 'potential_duplicate' THEN
                      jsonb_set(
                        w,
                        '{details,matches}',
                        COALESCE((
                          SELECT jsonb_agg(m)
                          FROM jsonb_array_elements(w->'details'->'matches') m
                          WHERE m->>'ulid' <> $1::text
                        ), '[]'::jsonb)
                      )
                    ELSE w
                  END AS new_w
           FROM jsonb_array_elements(warnings) WITH ORDINALITY AS t(w, idx)
         ) sub
       ),
       updated_at = NOW()
 WHERE event_id = (
         SELECT e.id FROM events e WHERE e.ulid = $2::text LIMIT 1
       )
   AND status = 'pending'
`

type DismissCompanionWarningMatchParams struct {
	EventUlid     string `json:"event_ulid"`
	CompanionUlid string `json:"companion_ulid"`
}

// Atomically remove any potential_duplicate match entry whose ulid equals event_ulid
// from the companion's pending review queue entry, identified by the companion's event ULID.
// Rebuilds the warnings JSONB in one UPDATE — no read-modify-write race.
func (q *Queries) DismissCompanionWarningMatch(ctx context.Context, arg DismissCompanionWarningMatchParams) error {
	_, err := q.db.Exec(ctx, dismissCompanionWarningMatch, arg.EventUlid, arg.CompanionUlid)
	return err
}

const dismissWarningMatchByReviewID = `-- name: DismissWarningMatchByReviewID :exec
UPDATE event_review_queue
   SET warnings = (
         SELECT COALESCE(jsonb_agg(new_w ORDER BY idx), '[]'::jsonb)
         FROM (
           SELECT idx,
                  CASE
                    WHEN w->>'code' = 'potential_duplicate' THEN
                      jsonb_set(
                        w,
                        '{details,matches}',
                        COALESCE((
                          SELECT jsonb_agg(m)
                          FROM jsonb_array_elements(w->'details'->'matches') m
                          WHERE m->>'ulid' <> $1::text
                        ), '[]'::jsonb)
                      )
                    ELSE w
                  END AS new_w
           FROM jsonb_array_elements(warnings) WITH ORDINALITY AS t(w, idx)
         ) sub
       ),
       updated_at = NOW()
 WHERE id = $2::int
`

type DismissWarningMatchByReviewIDParams struct {
	EventUlid string `json:"event_ulid"`
	ReviewID  int32  `json:"review_id"`
}

// Atomically remove any potential_duplicate match entry whose ulid equals event_ulid
// from a specific review queue entry identified by its primary key id.
// Narrower than DismissCompanionWarningMatch: targets exactly one row, preventing
// accidental modification of unrelated pending reviews on the same companion event.
func (q *Queries) DismissWarningMatchByReviewID(ctx context.Context, arg DismissWarningMatchByReviewIDParams) error {
	_, err := q.db.Exec(ctx, dismissWarningMatchByReviewID, arg.EventUlid, arg.ReviewID)
	return err
}

const findReviewByDedup = `-- name: FindReviewByDedup :one

SELECT r.id,
       r.event_id,
       e.ulid AS event_ulid,
       r.original_payload,
       r.normalized_payload,
       r.warnings,
       r.source_id,
       r.source_external_id,
       r.dedup_hash,
       r.event_start_time,
       r.event_end_time,
       r.status,
       r.reviewed_by,
       r.reviewed_at,
       r.review_notes,
       r.rejection_reason,
       r.created_at,
       r.updated_at,
       r.duplicate_of_event_id,
       dup.ulid AS duplicate_of_event_ulid
  FROM event_review_queue r
  JOIN events e ON e.id = r.event_id
  LEFT JOIN events dup ON dup.id = r.duplicate_of_event_id
 WHERE (
         ($1::text IS NOT NULL 
          AND $2::text IS NOT NULL 
          AND r.source_id = $1 
          AND r.source_external_id = $2)
         OR
         ($3::text IS NOT NULL 
          AND r.dedup_hash = $3)
       )
   AND r.status IN ('pending', 'rejected')
 ORDER BY r.created_at DESC
 LIMIT 1
`

type FindReviewByDedupParams struct {
	SourceID         pgtype.Text `json:"source_id"`
	SourceExternalID pgtype.Text `json:"source_external_id"`
	DedupHash        pgtype.Text `json:"dedup_hash"`
}

type FindReviewByDedupRow struct {
	ID                   int32              `json:"id"`
	EventID              pgtype.UUID        `json:"event_id"`
	EventUlid            string             `json:"event_ulid"`
	OriginalPayload      []byte             `json:"original_payload"`
	NormalizedPayload    []byte             `json:"normalized_payload"`
	Warnings             []byte             `json:"warnings"`
	SourceID             pgtype.Text        `json:"source_id"`
	SourceExternalID     pgtype.Text        `json:"source_external_id"`
	DedupHash            pgtype.Text        `json:"dedup_hash"`
	EventStartTime       pgtype.Timestamptz `json:"event_start_time"`
	EventEndTime         pgtype.Timestamptz `json:"event_end_time"`
	Status               string             `json:"status"`
	ReviewedBy           pgtype.Text        `json:"reviewed_by"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes          pgtype.Text        `json:"review_notes"`
	RejectionReason      pgtype.Text        `json:"rejection_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DuplicateOfEventID   pgtype.UUID        `json:"duplicate_of_event_id"`
	DuplicateOfEventUlid pgtype.Text        `json:"duplicate_of_event_ulid"`
}

// SQLc queries for event_review_queue domain.
// See docs/architecture/event-review-workflow.md for complete design.
// Find existing review by deduplication keys (checks source_external_id or dedup_hash)
func (q *Queries) FindReviewByDedup(ctx context.Context, arg FindReviewByDedupParams) (FindReviewByDedupRow, error) {
	row := q.db.QueryRow(ctx, findReviewByDedup, arg.SourceID, arg.SourceExternalID, arg.DedupHash)
	var i FindReviewByDedupRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventUlid,
		&i.OriginalPayload,
		&i.NormalizedPayload,
		&i.Warnings,
		&i.SourceID,
		&i.SourceExternalID,
		&i.DedupHash,
		&i.EventStartTime,
		&i.EventEndTime,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DuplicateOfEventID,
		&i.DuplicateOfEventUlid,
	)
	return i, err
}

const getPendingReviewByEventUlid = `-- name: GetPendingReviewByEventUlid :one
SELECT r.id,
       r.event_id,
       e.ulid AS event_ulid,
       r.original_payload,
       r.normalized_payload,
       r.warnings,
       r.source_id,
       r.source_external_id,
       r.dedup_hash,
       r.event_start_time,
       r.event_end_time,
       r.status,
       r.reviewed_by,
       r.reviewed_at,
       r.review_notes,
       r.rejection_reason,
       r.created_at,
       r.updated_at,
       r.duplicate_of_event_id,
       dup.ulid AS duplicate_of_event_ulid
  FROM event_review_queue r
  JOIN events e ON e.id = r.event_id
  LEFT JOIN events dup ON dup.id = r.duplicate_of_event_id
 WHERE e.ulid = $1
   AND r.status = 'pending'
 LIMIT 1
`

type GetPendingReviewByEventUlidRow struct {
	ID                   int32              `json:"id"`
	EventID              pgtype.UUID        `json:"event_id"`
	EventUlid            string             `json:"event_ulid"`
	OriginalPayload      []byte             `json:"original_payload"`
	NormalizedPayload    []byte             `json:"normalized_payload"`
	Warnings             []byte             `json:"warnings"`
	SourceID             pgtype.Text        `json:"source_id"`
	SourceExternalID     pgtype.Text        `json:"source_external_id"`
	DedupHash            pgtype.Text        `json:"dedup_hash"`
	EventStartTime       pgtype.Timestamptz `json:"event_start_time"`
	EventEndTime         pgtype.Timestamptz `json:"event_end_time"`
	Status               string             `json:"status"`
	ReviewedBy           pgtype.Text        `json:"reviewed_by"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes          pgtype.Text        `json:"review_notes"`
	RejectionReason      pgtype.Text        `json:"rejection_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DuplicateOfEventID   pgtype.UUID        `json:"duplicate_of_event_id"`
	DuplicateOfEventUlid pgtype.Text        `json:"duplicate_of_event_ulid"`
}

// Get the pending review queue entry for an event by its ULID, if any.
func (q *Queries) GetPendingReviewByEventUlid(ctx context.Context, eventUlid string) (GetPendingReviewByEventUlidRow, error) {
	row := q.db.QueryRow(ctx, getPendingReviewByEventUlid, eventUlid)
	var i GetPendingReviewByEventUlidRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventUlid,
		&i.OriginalPayload,
		&i.NormalizedPayload,
		&i.Warnings,
		&i.SourceID,
		&i.SourceExternalID,
		&i.DedupHash,
		&i.EventStartTime,
		&i.EventEndTime,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DuplicateOfEventID,
		&i.DuplicateOfEventUlid,
	)
	return i, err
}

const getPendingReviewByEventUlidAndDuplicateUlid = `-- name: GetPendingReviewByEventUlidAndDuplicateUlid :one
SELECT r.id,
       r.event_id,
       e.ulid AS event_ulid,
       r.original_payload,
       r.normalized_payload,
       r.warnings,
       r.source_id,
       r.source_external_id,
       r.dedup_hash,
       r.event_start_time,
       r.event_end_time,
       r.status,
       r.reviewed_by,
       r.reviewed_at,
       r.review_notes,
       r.rejection_reason,
       r.created_at,
       r.updated_at,
       r.duplicate_of_event_id,
       dup.ulid AS duplicate_of_event_ulid
  FROM event_review_queue r
  JOIN events e ON e.id = r.event_id
  LEFT JOIN events dup ON dup.id = r.duplicate_of_event_id
 WHERE e.ulid = $1
   AND r.status = 'pending'
   AND dup.ulid = $2
 LIMIT 1
`

type GetPendingReviewByEventUlidAndDuplicateUlidParams struct {
	EventUlid     string `json:"event_ulid"`
	DuplicateUlid string `json:"duplicate_ulid"`
}

type GetPendingReviewByEventUlidAndDuplicateUlidRow struct {
	ID                   int32              `json:"id"`
	EventID              pgtype.UUID        `json:"event_id"`
	EventUlid            string             `json:"event_ulid"`
	OriginalPayload      []byte             `json:"original_payload"`
	NormalizedPayload    []byte             `json:"normalized_payload"`
	Warnings             []byte             `json:"warnings"`
	SourceID             pgtype.Text        `json:"source_id"`
	SourceExternalID     pgtype.Text        `json:"source_external_id"`
	DedupHash            pgtype.Text        `json:"dedup_hash"`
	EventStartTime       pgtype.Timestamptz `json:"event_start_time"`
	EventEndTime         pgtype.Timestamptz `json:"event_end_time"`
	Status               string             `json:"status"`
	ReviewedBy           pgtype.Text        `json:"reviewed_by"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes          pgtype.Text        `json:"review_notes"`
	RejectionReason      pgtype.Text        `json:"rejection_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DuplicateOfEventID   pgtype.UUID        `json:"duplicate_of_event_id"`
	DuplicateOfEventUlid pgtype.Text        `json:"duplicate_of_event_ulid"`
}

// Get the pending review queue entry for an event by its ULID, narrowed to the
// specific companion whose duplicate_of_event_id points to the counterpart event.
// Used by the add-occurrence workflow to avoid picking an unrelated pending review
// when the same event has multiple pending review rows.
func (q *Queries) GetPendingReviewByEventUlidAndDuplicateUlid(ctx context.Context, arg GetPendingReviewByEventUlidAndDuplicateUlidParams) (GetPendingReviewByEventUlidAndDuplicateUlidRow, error) {
	row := q.db.QueryRow(ctx, getPendingReviewByEventUlidAndDuplicateUlid, arg.EventUlid, arg.DuplicateUlid)
	var i GetPendingReviewByEventUlidAndDuplicateUlidRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventUlid,
		&i.OriginalPayload,
		&i.NormalizedPayload,
		&i.Warnings,
		&i.SourceID,
		&i.SourceExternalID,
		&i.DedupHash,
		&i.EventStartTime,
		&i.EventEndTime,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DuplicateOfEventID,
		&i.DuplicateOfEventUlid,
	)
	return i, err
}

const getReviewQueueEntry = `-- name: GetReviewQueueEntry :one
SELECT r.id,
       r.event_id,
       e.ulid AS event_ulid,
       r.original_payload,
       r.normalized_payload,
       r.warnings,
       r.source_id,
       r.source_external_id,
       r.dedup_hash,
       r.event_start_time,
       r.event_end_time,
       r.status,
       r.reviewed_by,
       r.reviewed_at,
       r.review_notes,
       r.rejection_reason,
       r.created_at,
       r.updated_at,
       r.duplicate_of_event_id,
       dup.ulid AS duplicate_of_event_ulid
  FROM event_review_queue r
  JOIN events e ON e.id = r.event_id
  LEFT JOIN events dup ON dup.id = r.duplicate_of_event_id
 WHERE r.id = $1
`

type GetReviewQueueEntryRow struct {
	ID                   int32              `json:"id"`
	EventID              pgtype.UUID        `json:"event_id"`
	EventUlid            string             `json:"event_ulid"`
	OriginalPayload      []byte             `json:"original_payload"`
	NormalizedPayload    []byte             `json:"normalized_payload"`
	Warnings             []byte             `json:"warnings"`
	SourceID             pgtype.Text        `json:"source_id"`
	SourceExternalID     pgtype.Text        `json:"source_external_id"`
	DedupHash            pgtype.Text        `json:"dedup_hash"`
	EventStartTime       pgtype.Timestamptz `json:"event_start_time"`
	EventEndTime         pgtype.Timestamptz `json:"event_end_time"`
	Status               string             `json:"status"`
	ReviewedBy           pgtype.Text        `json:"reviewed_by"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes          pgtype.Text        `json:"review_notes"`
	RejectionReason      pgtype.Text        `json:"rejection_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DuplicateOfEventID   pgtype.UUID        `json:"duplicate_of_event_id"`
	DuplicateOfEventUlid pgtype.Text        `json:"duplicate_of_event_ulid"`
}

// Get single review by ID
func (q *Queries) GetReviewQueueEntry(ctx context.Context, id int32) (GetReviewQueueEntryRow, error) {
	row := q.db.QueryRow(ctx, getReviewQueueEntry, id)
	var i GetReviewQueueEntryRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventUlid,
		&i.OriginalPayload,
		&i.NormalizedPayload,
		&i.Warnings,
		&i.SourceID,
		&i.SourceExternalID,
		&i.DedupHash,
		&i.EventStartTime,
		&i.EventEndTime,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DuplicateOfEventID,
		&i.DuplicateOfEventUlid,
	)
	return i, err
}

const listReviewQueue = `-- name: ListReviewQueue :many
SELECT r.id,
       r.event_id,
       e.ulid AS event_ulid,
       r.original_payload,
       r.normalized_payload,
       r.warnings,
       r.source_id,
       r.source_external_id,
       r.dedup_hash,
       r.event_start_time,
       r.event_end_time,
       r.status,
       r.reviewed_by,
       r.reviewed_at,
       r.review_notes,
       r.rejection_reason,
       r.created_at,
       r.updated_at,
       r.duplicate_of_event_id,
       dup.ulid AS duplicate_of_event_ulid
  FROM event_review_queue r
  JOIN events e ON e.id = r.event_id
  LEFT JOIN events dup ON dup.id = r.duplicate_of_event_id
 WHERE ($1::text IS NULL OR r.status = $1)
   AND ($2::integer IS NULL OR r.id > $2)
 ORDER BY r.id ASC
 LIMIT $3
`

type ListReviewQueueParams struct {
	Status  pgtype.Text `json:"status"`
	AfterID pgtype.Int4 `json:"after_id"`
	Limit   int32       `json:"limit"`
}

type ListReviewQueueRow struct {
	ID                   int32              `json:"id"`
	EventID              pgtype.UUID        `json:"event_id"`
	EventUlid            string             `json:"event_ulid"`
	OriginalPayload      []byte             `json:"original_payload"`
	NormalizedPayload    []byte             `json:"normalized_payload"`
	Warnings             []byte             `json:"warnings"`
	SourceID             pgtype.Text        `json:"source_id"`
	SourceExternalID     pgtype.Text        `json:"source_external_id"`
	DedupHash            pgtype.Text        `json:"dedup_hash"`
	EventStartTime       pgtype.Timestamptz `json:"event_start_time"`
	EventEndTime         pgtype.Timestamptz `json:"event_end_time"`
	Status               string             `json:"status"`
	ReviewedBy           pgtype.Text        `json:"reviewed_by"`
	ReviewedAt           pgtype.Timestamptz `json:"reviewed_at"`
	ReviewNotes          pgtype.Text        `json:"review_notes"`
	RejectionReason      pgtype.Text        `json:"rejection_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DuplicateOfEventID   pgtype.UUID        `json:"duplicate_of_event_id"`
	DuplicateOfEventUlid pgtype.Text        `json:"duplicate_of_event_ulid"`
}

// List reviews with pagination and status filter
func (q *Queries) ListReviewQueue(ctx context.Context, arg ListReviewQueueParams) ([]ListReviewQueueRow, error) {
	rows, err := q.db.Query(ctx, listReviewQueue, arg.Status, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewQueueRow{}
	for rows.Next() {
		var i ListReviewQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventUlid,
			&i.OriginalPayload,
			&i.NormalizedPayload,
			&i.Warnings,
			&i.SourceID,
			&i.SourceExternalID,
			&i.DedupHash,
			&i.EventStartTime,
			&i.EventEndTime,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewNotes,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DuplicateOfEventID,
			&i.DuplicateOfEventUlid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUnreviewedEventsAsDeleted = `-- name: MarkUnreviewedEventsAsDeleted :exec
UPDATE events
   SET lifecycle_state = 'deleted',
       deleted_at = NOW(),
       deletion_reason = 'Expired from review queue - event started before review',
       updated_at = NOW()
 WHERE id IN (
   SELECT event_id FROM event_review_queue
   WHERE status = 'pending' AND event_start_time < NOW()
 )
   AND lifecycle_state = 'pending_review'
`

// Mark events as deleted before cleaning up their pending reviews
func (q *Queries) MarkUnreviewedEventsAsDeleted(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markUnreviewedEventsAsDeleted)
	return err
}

const rejectReview = `-- name: RejectReview :one
UPDATE event_review_queue
   SET status = 'rejected',
       reviewed_by = $1,
       reviewed_at = NOW(),
       rejection_reason = $2,
       updated_at = NOW()
 WHERE id = $3
   AND status = 'pending'
RETURNING id, event_id, original_payload, normalized_payload, warnings, source_id, source_external_id, dedup_hash, event_start_time, event_end_time, status, reviewed_by, reviewed_at, review_notes, rejection_reason, created_at, updated_at, duplicate_of_event_id
`

type RejectReviewParams struct {
	ReviewedBy pgtype.Text `json:"reviewed_by"`
	Reason     pgtype.Text `json:"reason"`
	ID         int32       `json:"id"`
}

// Mark review as rejected
func (q *Queries) RejectReview(ctx context.Context, arg RejectReviewParams) (EventReviewQueue, error) {
	row := q.db.QueryRow(ctx, rejectReview, arg.ReviewedBy, arg.Reason, arg.ID)
	var i EventReviewQueue
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OriginalPayload,
		&i.NormalizedPayload,
		&i.Warnings,
		&i.SourceID,
		&i.SourceExternalID,
		&i.DedupHash,
		&i.EventStartTime,
		&i.EventEndTime,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DuplicateOfEventID,
	)
	return i, err
}

const stripRetiredDupWarnings = `-- name: StripRetiredDupWarnings :one
WITH stripped AS (
  SELECT COALESCE(jsonb_agg(new_w ORDER BY idx), '[]'::jsonb) AS warnings
  FROM (
    SELECT idx,
           CASE
             WHEN w->>'code' = 'potential_duplicate' THEN (
               SELECT CASE WHEN jsonb_array_length(rebuilt) = 0 THEN NULL
                           ELSE jsonb_set(w, '{details,matches}', rebuilt)
                      END
               FROM (
                 SELECT COALESCE(jsonb_agg(m), '[]'::jsonb) AS rebuilt
                 FROM jsonb_array_elements(w->'details'->'matches') m
                 WHERE NOT (m->>'ulid' = ANY($1::text[]))
               ) _
             )
             WHEN w->>'code' = 'cross_week_series_companion'
                  AND w->'details'->>'companion_ulid' = ANY($1::text[]) THEN NULL
             ELSE w
           END AS new_w
    FROM event_review_queue rq,
         jsonb_array_elements(rq.warnings) WITH ORDINALITY AS t(w, idx)
    WHERE rq.id = $2::int
      AND NOT (
        w->>'code' = 'near_duplicate_of_new_event'
        AND EXISTS (
          SELECT 1 FROM events WHERE id = rq.duplicate_of_event_id
          AND ulid = ANY($1::text[])
        )
      )
  ) sub
  WHERE new_w IS NOT NULL
)
UPDATE event_review_queue
   SET warnings = stripped.warnings,
       duplicate_of_event_id = CASE
         WHEN EXISTS (
           SELECT 1 FROM events WHERE id = event_review_queue.duplicate_of_event_id
           AND ulid = ANY($1::text[])
         ) THEN NULL
         ELSE duplicate_of_event_id
       END,
       updated_at = NOW()
  FROM stripped
 WHERE id = $2::int
   AND status = 'pending'
RETURNING (stripped.warnings = '[]'::jsonb) AS warnings_empty
`

type StripRetiredDupWarningsParams struct {
	RetireUlids []string `json:"retire_ulids"`
	ReviewID    int32    `json:"review_id"`
}

// Atomically strips all duplicate warning entries referencing any of the given retire_ulids
// from a specific review row. Handles three warning types:
//
//	near_duplicate_of_new_event  — stripped when duplicate_of_event_id points to a retired event
//	potential_duplicate          — specific match entries filtered; warning nullified when matches empty
//	cross_week_series_companion  — stripped when details->>'companion_ulid' is in the retire set
//
// Also clears duplicate_of_event_id if it points to a retired event.
// Returns true (warnings_empty) when the resulting warnings array is empty after stripping.
// Note: companion replacement is handled in Go after SQL returns.
func (q *Queries) StripRetiredDupWarnings(ctx context.Context, arg StripRetiredDupWarningsParams) (bool, error) {
	row := q.db.QueryRow(ctx, stripRetiredDupWarnings, arg.RetireUlids, arg.ReviewID)
	var warnings_empty bool
	err := row.Scan(&warnings_empty)
	return warnings_empty, err
}

const updateReviewQueueEntry = `-- name: UpdateReviewQueueEntry :one
UPDATE event_review_queue
   SET original_payload = COALESCE($1, original_payload),
       normalized_payload = COALESCE($2, normalized_payload),
       warnings = COALESCE($3, warnings),
       duplicate_of_event_id = CASE
                                 WHEN $4::boolean IS TRUE THEN NULL
                                 ELSE COALESCE($5, duplicate_of_event_id)
                               END,
       updated_at = NOW()
 WHERE id = $6
RETURNING id, event_id, original_payload, normalized_payload, warnings, source_id, source_external_id, dedup_hash, event_start_time, event_end_time, status, reviewed_by, reviewed_at, review_notes, rejection_reason, created_at, updated_at, duplicate_of_event_id
`

type UpdateReviewQueueEntryParams struct {
	OriginalPayload    []byte      `json:"original_payload"`
	NormalizedPayload  []byte      `json:"normalized_payload"`
	Warnings           []byte      `json:"warnings"`
	ClearDuplicateOf   pgtype.Bool `json:"clear_duplicate_of"`
	DuplicateOfEventID pgtype.UUID `json:"duplicate_of_event_id"`
	ID                 int32       `json:"id"`
}

// Update existing review entry (for resubmissions with same issues).
// Pass clear_duplicate_of=TRUE to set duplicate_of_event_id to NULL;
// otherwise pass a new UUID via duplicate_of_event_id or leave both NULL to keep the existing value.
func (q *Queries) UpdateReviewQueueEntry(ctx context.Context, arg UpdateReviewQueueEntryParams) (EventReviewQueue, error) {
	row := q.db.QueryRow(ctx, updateReviewQueueEntry,
		arg.OriginalPayload,
		arg.NormalizedPayload,
		arg.Warnings,
		arg.ClearDuplicateOf,
		arg.DuplicateOfEventID,
		arg.ID,
	)
	var i EventReviewQueue
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OriginalPayload,
		&i.NormalizedPayload,
		&i.Warnings,
		&i.SourceID,
		&i.SourceExternalID,
		&i.DedupHash,
		&i.EventStartTime,
		&i.EventEndTime,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DuplicateOfEventID,
	)
	return i, err
}

const updateReviewWarnings = `-- name: UpdateReviewWarnings :exec
UPDATE event_review_queue
   SET warnings = $1,
       updated_at = NOW()
 WHERE id = $2
`

type UpdateReviewWarningsParams struct {
	Warnings []byte `json:"warnings"`
	ID       int32  `json:"id"`
}

// Update only the warnings JSON of a review queue entry (used for companion warning dismissal).
func (q *Queries) UpdateReviewWarnings(ctx context.Context, arg UpdateReviewWarningsParams) error {
	_, err := q.db.Exec(ctx, updateReviewWarnings, arg.Warnings, arg.ID)
	return err
}
