// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const demotePrimaryAndSupersede = `-- name: DemotePrimaryAndSupersede :exec
UPDATE entity_identifiers SET is_primary = false, superseded_by_id = $1, updated_at = now()
WHERE entity_type = $2 AND entity_id = $3
  AND authority_code = $4 AND is_primary AND id <> $1
`

type DemotePrimaryAndSupersedeParams struct {
	WinnerID      pgtype.Int4 `json:"winner_id"`
	EntityType    string      `json:"entity_type"`
	EntityID      string      `json:"entity_id"`
	AuthorityCode string      `json:"authority_code"`
}

// Demote every primary in the group except the winner, recording the superseding row.
// superseded_by_id records the *immediate successor* at demotion time, not necessarily
// the current primary: if that successor is later demoted, it keeps pointing at it.
func (q *Queries) DemotePrimaryAndSupersede(ctx context.Context, arg DemotePrimaryAndSupersedeParams) error {
	_, err := q.db.Exec(ctx, demotePrimaryAndSupersede,
		arg.WinnerID,
		arg.EntityType,
		arg.EntityID,
		arg.AuthorityCode,
	)
	return err
}

const insertIdentityNotDuplicate = `-- name: InsertIdentityNotDuplicate :exec
INSERT INTO identity_not_duplicates (entity_type, id_a, id_b, evidence_fingerprint, decision_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (entity_type, id_a, id_b) DO UPDATE SET
    evidence_fingerprint = EXCLUDED.evidence_fingerprint,
    decision_id = EXCLUDED.decision_id,
    created_at = now(),
    created_by = EXCLUDED.created_by
`

type InsertIdentityNotDuplicateParams struct {
	EntityType          string      `json:"entity_type"`
	IDA                 string      `json:"id_a"`
	IDB                 string      `json:"id_b"`
	EvidenceFingerprint string      `json:"evidence_fingerprint"`
	DecisionID          pgtype.Text `json:"decision_id"`
	CreatedBy           string      `json:"created_by"`
}

// Record a not-duplicate pair; re-decision refreshes the evidence fingerprint and decision.
func (q *Queries) InsertIdentityNotDuplicate(ctx context.Context, arg InsertIdentityNotDuplicateParams) error {
	_, err := q.db.Exec(ctx, insertIdentityNotDuplicate,
		arg.EntityType,
		arg.IDA,
		arg.IDB,
		arg.EvidenceFingerprint,
		arg.DecisionID,
		arg.CreatedBy,
	)
	return err
}

const listEntityIdentifiersForUpdate = `-- name: ListEntityIdentifiersForUpdate :many
SELECT ei.id, ei.authority_code, ei.identifier_uri, ei.reconciliation_method,
       ei.confidence, ei.observed_at, ei.is_primary, ei.source,
       a.trust_level, a.priority_order
FROM entity_identifiers ei
JOIN knowledge_graph_authorities a ON a.authority_code = ei.authority_code
WHERE ei.entity_type = $1
  AND ei.entity_id = $2
ORDER BY ei.id
FOR UPDATE OF ei
`

type ListEntityIdentifiersForUpdateParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

type ListEntityIdentifiersForUpdateRow struct {
	ID                   int32              `json:"id"`
	AuthorityCode        string             `json:"authority_code"`
	IdentifierUri        string             `json:"identifier_uri"`
	ReconciliationMethod string             `json:"reconciliation_method"`
	Confidence           pgtype.Numeric     `json:"confidence"`
	ObservedAt           pgtype.Timestamptz `json:"observed_at"`
	IsPrimary            bool               `json:"is_primary"`
	Source               pgtype.Text        `json:"source"`
	TrustLevel           int32              `json:"trust_level"`
	PriorityOrder        int32              `json:"priority_order"`
}

// Load all of an entity's identifier observations joined with authority
// trust/priority. FOR UPDATE OF ei serializes the entity's identifier rows against
// concurrent elections. Used by the transactional merge path to reassign, dedupe,
// and re-elect one primary per authority.
func (q *Queries) ListEntityIdentifiersForUpdate(ctx context.Context, arg ListEntityIdentifiersForUpdateParams) ([]ListEntityIdentifiersForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listEntityIdentifiersForUpdate, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntityIdentifiersForUpdateRow{}
	for rows.Next() {
		var i ListEntityIdentifiersForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorityCode,
			&i.IdentifierUri,
			&i.ReconciliationMethod,
			&i.Confidence,
			&i.ObservedAt,
			&i.IsPrimary,
			&i.Source,
			&i.TrustLevel,
			&i.PriorityOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupIdentifiersForUpdate = `-- name: ListGroupIdentifiersForUpdate :many
SELECT ei.id, ei.authority_code, ei.identifier_uri, ei.reconciliation_method,
       ei.confidence, ei.observed_at, ei.is_primary, ei.source,
       a.trust_level, a.priority_order
FROM entity_identifiers ei
JOIN knowledge_graph_authorities a ON a.authority_code = ei.authority_code
WHERE ei.entity_type = $1
  AND ei.entity_id = $2
  AND ei.authority_code = $3
ORDER BY ei.id
FOR UPDATE OF ei
`

type ListGroupIdentifiersForUpdateParams struct {
	EntityType    string `json:"entity_type"`
	EntityID      string `json:"entity_id"`
	AuthorityCode string `json:"authority_code"`
}

type ListGroupIdentifiersForUpdateRow struct {
	ID                   int32              `json:"id"`
	AuthorityCode        string             `json:"authority_code"`
	IdentifierUri        string             `json:"identifier_uri"`
	ReconciliationMethod string             `json:"reconciliation_method"`
	Confidence           pgtype.Numeric     `json:"confidence"`
	ObservedAt           pgtype.Timestamptz `json:"observed_at"`
	IsPrimary            bool               `json:"is_primary"`
	Source               pgtype.Text        `json:"source"`
	TrustLevel           int32              `json:"trust_level"`
	PriorityOrder        int32              `json:"priority_order"`
}

// Load one authority group's observations joined with authority trust/priority.
// FOR UPDATE OF ei serializes the group rows against concurrent elections.
func (q *Queries) ListGroupIdentifiersForUpdate(ctx context.Context, arg ListGroupIdentifiersForUpdateParams) ([]ListGroupIdentifiersForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listGroupIdentifiersForUpdate, arg.EntityType, arg.EntityID, arg.AuthorityCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupIdentifiersForUpdateRow{}
	for rows.Next() {
		var i ListGroupIdentifiersForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorityCode,
			&i.IdentifierUri,
			&i.ReconciliationMethod,
			&i.Confidence,
			&i.ObservedAt,
			&i.IsPrimary,
			&i.Source,
			&i.TrustLevel,
			&i.PriorityOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIdentityGroup = `-- name: LockIdentityGroup :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

// Serialize concurrent elections on one (entity_type, entity_id, authority_code) group.
// pg_advisory_xact_lock is released automatically at transaction end.
func (q *Queries) LockIdentityGroup(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, lockIdentityGroup, key)
	return err
}

const setPrimary = `-- name: SetPrimary :exec
UPDATE entity_identifiers SET is_primary = true, superseded_by_id = NULL, updated_at = now()
WHERE id = $1
`

// Unconditionally mark one identifier row as the group's primary and clear its supersession.
func (q *Queries) SetPrimary(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setPrimary, id)
	return err
}

const upsertObservation = `-- name: UpsertObservation :one

INSERT INTO entity_identifiers (entity_type, entity_id, authority_code, identifier_uri, confidence, reconciliation_method, is_canonical, metadata, observed_at, is_primary, source)
VALUES ($1, $2, $3, $4, $5, $6, false, $7, now(), false, $8)
ON CONFLICT (entity_type, entity_id, authority_code, identifier_uri)
DO UPDATE SET
    confidence = EXCLUDED.confidence,
    reconciliation_method = EXCLUDED.reconciliation_method,
    is_canonical = false,
    metadata = COALESCE(EXCLUDED.metadata, entity_identifiers.metadata),
    observed_at = now(),
    source = EXCLUDED.source,
    updated_at = now()
RETURNING id, entity_type, entity_id, authority_code, identifier_uri, confidence, reconciliation_method, is_canonical, metadata, created_at, updated_at, observed_at, is_primary, superseded_by_id, source
`

type UpsertObservationParams struct {
	EntityType           string         `json:"entity_type"`
	EntityID             string         `json:"entity_id"`
	AuthorityCode        string         `json:"authority_code"`
	IdentifierUri        string         `json:"identifier_uri"`
	Confidence           pgtype.Numeric `json:"confidence"`
	ReconciliationMethod string         `json:"reconciliation_method"`
	Metadata             []byte         `json:"metadata"`
	Source               pgtype.Text    `json:"source"`
}

// SQLc queries for entity identity primitives.
// See: specs/007-entity-identity-adjudication/spec-phase1.md (Task 1/2)
// Insert or refresh an identifier observation without disturbing the primary slot.
// metadata is non-destructive on conflict: a NULL incoming metadata (the common case —
// RecordObservation does not carry metadata) preserves the existing row's JSONB.
func (q *Queries) UpsertObservation(ctx context.Context, arg UpsertObservationParams) (EntityIdentifier, error) {
	row := q.db.QueryRow(ctx, upsertObservation,
		arg.EntityType,
		arg.EntityID,
		arg.AuthorityCode,
		arg.IdentifierUri,
		arg.Confidence,
		arg.ReconciliationMethod,
		arg.Metadata,
		arg.Source,
	)
	var i EntityIdentifier
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.AuthorityCode,
		&i.IdentifierUri,
		&i.Confidence,
		&i.ReconciliationMethod,
		&i.IsCanonical,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.IsPrimary,
		&i.SupersededByID,
		&i.Source,
	)
	return i, err
}
