// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllOrganizations = `-- name: CountAllOrganizations :one
SELECT COUNT(*) FROM organizations WHERE deleted_at IS NULL
`

func (q *Queries) CountAllOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganizationTombstone = `-- name: CreateOrganizationTombstone :exec
INSERT INTO organization_tombstones (organization_id, organization_uri, deleted_at, deletion_reason, superseded_by_uri, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOrganizationTombstoneParams struct {
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	OrganizationUri string             `json:"organization_uri"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DeletionReason  pgtype.Text        `json:"deletion_reason"`
	SupersededByUri pgtype.Text        `json:"superseded_by_uri"`
	Payload         []byte             `json:"payload"`
}

func (q *Queries) CreateOrganizationTombstone(ctx context.Context, arg CreateOrganizationTombstoneParams) error {
	_, err := q.db.Exec(ctx, createOrganizationTombstone,
		arg.OrganizationID,
		arg.OrganizationUri,
		arg.DeletedAt,
		arg.DeletionReason,
		arg.SupersededByUri,
		arg.Payload,
	)
	return err
}

const getOrganizationByULID = `-- name: GetOrganizationByULID :one
SELECT o.id, o.ulid, o.name, o.legal_name, o.alternate_name, o.description, o.email, o.telephone, o.url, o.street_address, o.address_locality, o.address_region, o.postal_code, o.address_country, o.organization_type, o.founding_date, o.origin_node_id, o.confidence, o.created_at, o.updated_at, o.deleted_at, o.deletion_reason, o.federation_uri, o.normalized_name, o.merged_into_id
  FROM organizations o
 WHERE o.ulid = $1
`

type GetOrganizationByULIDRow struct {
	Organization Organization `json:"organization"`
}

func (q *Queries) GetOrganizationByULID(ctx context.Context, ulid string) (GetOrganizationByULIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByULID, ulid)
	var i GetOrganizationByULIDRow
	err := row.Scan(
		&i.Organization.ID,
		&i.Organization.Ulid,
		&i.Organization.Name,
		&i.Organization.LegalName,
		&i.Organization.AlternateName,
		&i.Organization.Description,
		&i.Organization.Email,
		&i.Organization.Telephone,
		&i.Organization.Url,
		&i.Organization.StreetAddress,
		&i.Organization.AddressLocality,
		&i.Organization.AddressRegion,
		&i.Organization.PostalCode,
		&i.Organization.AddressCountry,
		&i.Organization.OrganizationType,
		&i.Organization.FoundingDate,
		&i.Organization.OriginNodeID,
		&i.Organization.Confidence,
		&i.Organization.CreatedAt,
		&i.Organization.UpdatedAt,
		&i.Organization.DeletedAt,
		&i.Organization.DeletionReason,
		&i.Organization.FederationUri,
		&i.Organization.NormalizedName,
		&i.Organization.MergedIntoID,
	)
	return i, err
}

const getOrganizationTombstoneByULID = `-- name: GetOrganizationTombstoneByULID :one
SELECT t.id,
       t.organization_id,
       t.organization_uri,
       t.deleted_at,
       t.deletion_reason,
       t.superseded_by_uri,
       t.payload
  FROM organization_tombstones t
  JOIN organizations o ON o.id = t.organization_id
 WHERE o.ulid = $1
 ORDER BY t.deleted_at DESC
 LIMIT 1
`

func (q *Queries) GetOrganizationTombstoneByULID(ctx context.Context, ulid string) (OrganizationTombstone, error) {
	row := q.db.QueryRow(ctx, getOrganizationTombstoneByULID, ulid)
	var i OrganizationTombstone
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrganizationUri,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.SupersededByUri,
		&i.Payload,
	)
	return i, err
}

const listOrganizationsByCreatedAt = `-- name: ListOrganizationsByCreatedAt :many

SELECT o.id, o.ulid, o.name, o.legal_name, o.alternate_name, o.description, o.email, o.telephone, o.url, o.street_address, o.address_locality, o.address_region, o.postal_code, o.address_country, o.organization_type, o.founding_date, o.origin_node_id, o.confidence, o.created_at, o.updated_at, o.deleted_at, o.deletion_reason, o.federation_uri, o.normalized_name, o.merged_into_id
  FROM organizations o
 WHERE o.deleted_at IS NULL
   AND ($1::text IS NULL OR o.address_locality ILIKE '%' || $1 || '%')
   AND ($2::text IS NULL OR o.name ILIKE '%' || $2 || '%' OR o.legal_name ILIKE '%' || $2 || '%')
   AND (
     $3::timestamptz IS NULL OR
     o.created_at > $3::timestamptz OR
     (o.created_at = $3::timestamptz AND o.ulid > $4)
   )
 ORDER BY o.created_at ASC, o.ulid ASC
 LIMIT $5
`

type ListOrganizationsByCreatedAtParams struct {
	City            pgtype.Text        `json:"city"`
	Query           pgtype.Text        `json:"query"`
	CursorTimestamp pgtype.Timestamptz `json:"cursor_timestamp"`
	CursorUlid      pgtype.Text        `json:"cursor_ulid"`
	Limit           int32              `json:"limit"`
}

type ListOrganizationsByCreatedAtRow struct {
	Organization Organization `json:"organization"`
}

// SQLc queries for organizations domain.
func (q *Queries) ListOrganizationsByCreatedAt(ctx context.Context, arg ListOrganizationsByCreatedAtParams) ([]ListOrganizationsByCreatedAtRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByCreatedAt,
		arg.City,
		arg.Query,
		arg.CursorTimestamp,
		arg.CursorUlid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsByCreatedAtRow{}
	for rows.Next() {
		var i ListOrganizationsByCreatedAtRow
		if err := rows.Scan(
			&i.Organization.ID,
			&i.Organization.Ulid,
			&i.Organization.Name,
			&i.Organization.LegalName,
			&i.Organization.AlternateName,
			&i.Organization.Description,
			&i.Organization.Email,
			&i.Organization.Telephone,
			&i.Organization.Url,
			&i.Organization.StreetAddress,
			&i.Organization.AddressLocality,
			&i.Organization.AddressRegion,
			&i.Organization.PostalCode,
			&i.Organization.AddressCountry,
			&i.Organization.OrganizationType,
			&i.Organization.FoundingDate,
			&i.Organization.OriginNodeID,
			&i.Organization.Confidence,
			&i.Organization.CreatedAt,
			&i.Organization.UpdatedAt,
			&i.Organization.DeletedAt,
			&i.Organization.DeletionReason,
			&i.Organization.FederationUri,
			&i.Organization.NormalizedName,
			&i.Organization.MergedIntoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByCreatedAtDesc = `-- name: ListOrganizationsByCreatedAtDesc :many
SELECT o.id, o.ulid, o.name, o.legal_name, o.alternate_name, o.description, o.email, o.telephone, o.url, o.street_address, o.address_locality, o.address_region, o.postal_code, o.address_country, o.organization_type, o.founding_date, o.origin_node_id, o.confidence, o.created_at, o.updated_at, o.deleted_at, o.deletion_reason, o.federation_uri, o.normalized_name, o.merged_into_id
  FROM organizations o
 WHERE o.deleted_at IS NULL
   AND ($1::text IS NULL OR o.address_locality ILIKE '%' || $1 || '%')
   AND ($2::text IS NULL OR o.name ILIKE '%' || $2 || '%' OR o.legal_name ILIKE '%' || $2 || '%')
   AND (
     $3::timestamptz IS NULL OR
     o.created_at < $3::timestamptz OR
     (o.created_at = $3::timestamptz AND o.ulid > $4)
   )
 ORDER BY o.created_at DESC, o.ulid ASC
 LIMIT $5
`

type ListOrganizationsByCreatedAtDescParams struct {
	City            pgtype.Text        `json:"city"`
	Query           pgtype.Text        `json:"query"`
	CursorTimestamp pgtype.Timestamptz `json:"cursor_timestamp"`
	CursorUlid      pgtype.Text        `json:"cursor_ulid"`
	Limit           int32              `json:"limit"`
}

type ListOrganizationsByCreatedAtDescRow struct {
	Organization Organization `json:"organization"`
}

func (q *Queries) ListOrganizationsByCreatedAtDesc(ctx context.Context, arg ListOrganizationsByCreatedAtDescParams) ([]ListOrganizationsByCreatedAtDescRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByCreatedAtDesc,
		arg.City,
		arg.Query,
		arg.CursorTimestamp,
		arg.CursorUlid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsByCreatedAtDescRow{}
	for rows.Next() {
		var i ListOrganizationsByCreatedAtDescRow
		if err := rows.Scan(
			&i.Organization.ID,
			&i.Organization.Ulid,
			&i.Organization.Name,
			&i.Organization.LegalName,
			&i.Organization.AlternateName,
			&i.Organization.Description,
			&i.Organization.Email,
			&i.Organization.Telephone,
			&i.Organization.Url,
			&i.Organization.StreetAddress,
			&i.Organization.AddressLocality,
			&i.Organization.AddressRegion,
			&i.Organization.PostalCode,
			&i.Organization.AddressCountry,
			&i.Organization.OrganizationType,
			&i.Organization.FoundingDate,
			&i.Organization.OriginNodeID,
			&i.Organization.Confidence,
			&i.Organization.CreatedAt,
			&i.Organization.UpdatedAt,
			&i.Organization.DeletedAt,
			&i.Organization.DeletionReason,
			&i.Organization.FederationUri,
			&i.Organization.NormalizedName,
			&i.Organization.MergedIntoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByName = `-- name: ListOrganizationsByName :many
SELECT o.id, o.ulid, o.name, o.legal_name, o.alternate_name, o.description, o.email, o.telephone, o.url, o.street_address, o.address_locality, o.address_region, o.postal_code, o.address_country, o.organization_type, o.founding_date, o.origin_node_id, o.confidence, o.created_at, o.updated_at, o.deleted_at, o.deletion_reason, o.federation_uri, o.normalized_name, o.merged_into_id
  FROM organizations o
 WHERE o.deleted_at IS NULL
   AND ($1::text IS NULL OR o.address_locality ILIKE '%' || $1 || '%')
   AND ($2::text IS NULL OR o.name ILIKE '%' || $2 || '%' OR o.legal_name ILIKE '%' || $2 || '%')
   AND (
     $3::text IS NULL OR
     o.name > $3 OR
     (o.name = $3 AND o.ulid > $4)
   )
 ORDER BY o.name ASC, o.ulid ASC
 LIMIT $5
`

type ListOrganizationsByNameParams struct {
	City       pgtype.Text `json:"city"`
	Query      pgtype.Text `json:"query"`
	CursorName pgtype.Text `json:"cursor_name"`
	CursorUlid pgtype.Text `json:"cursor_ulid"`
	Limit      int32       `json:"limit"`
}

type ListOrganizationsByNameRow struct {
	Organization Organization `json:"organization"`
}

func (q *Queries) ListOrganizationsByName(ctx context.Context, arg ListOrganizationsByNameParams) ([]ListOrganizationsByNameRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByName,
		arg.City,
		arg.Query,
		arg.CursorName,
		arg.CursorUlid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsByNameRow{}
	for rows.Next() {
		var i ListOrganizationsByNameRow
		if err := rows.Scan(
			&i.Organization.ID,
			&i.Organization.Ulid,
			&i.Organization.Name,
			&i.Organization.LegalName,
			&i.Organization.AlternateName,
			&i.Organization.Description,
			&i.Organization.Email,
			&i.Organization.Telephone,
			&i.Organization.Url,
			&i.Organization.StreetAddress,
			&i.Organization.AddressLocality,
			&i.Organization.AddressRegion,
			&i.Organization.PostalCode,
			&i.Organization.AddressCountry,
			&i.Organization.OrganizationType,
			&i.Organization.FoundingDate,
			&i.Organization.OriginNodeID,
			&i.Organization.Confidence,
			&i.Organization.CreatedAt,
			&i.Organization.UpdatedAt,
			&i.Organization.DeletedAt,
			&i.Organization.DeletionReason,
			&i.Organization.FederationUri,
			&i.Organization.NormalizedName,
			&i.Organization.MergedIntoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByNameDesc = `-- name: ListOrganizationsByNameDesc :many
SELECT o.id, o.ulid, o.name, o.legal_name, o.alternate_name, o.description, o.email, o.telephone, o.url, o.street_address, o.address_locality, o.address_region, o.postal_code, o.address_country, o.organization_type, o.founding_date, o.origin_node_id, o.confidence, o.created_at, o.updated_at, o.deleted_at, o.deletion_reason, o.federation_uri, o.normalized_name, o.merged_into_id
  FROM organizations o
 WHERE o.deleted_at IS NULL
   AND ($1::text IS NULL OR o.address_locality ILIKE '%' || $1 || '%')
   AND ($2::text IS NULL OR o.name ILIKE '%' || $2 || '%' OR o.legal_name ILIKE '%' || $2 || '%')
   AND (
     $3::text IS NULL OR
     o.name < $3 OR
     (o.name = $3 AND o.ulid > $4)
   )
 ORDER BY o.name DESC, o.ulid ASC
 LIMIT $5
`

type ListOrganizationsByNameDescParams struct {
	City       pgtype.Text `json:"city"`
	Query      pgtype.Text `json:"query"`
	CursorName pgtype.Text `json:"cursor_name"`
	CursorUlid pgtype.Text `json:"cursor_ulid"`
	Limit      int32       `json:"limit"`
}

type ListOrganizationsByNameDescRow struct {
	Organization Organization `json:"organization"`
}

func (q *Queries) ListOrganizationsByNameDesc(ctx context.Context, arg ListOrganizationsByNameDescParams) ([]ListOrganizationsByNameDescRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByNameDesc,
		arg.City,
		arg.Query,
		arg.CursorName,
		arg.CursorUlid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsByNameDescRow{}
	for rows.Next() {
		var i ListOrganizationsByNameDescRow
		if err := rows.Scan(
			&i.Organization.ID,
			&i.Organization.Ulid,
			&i.Organization.Name,
			&i.Organization.LegalName,
			&i.Organization.AlternateName,
			&i.Organization.Description,
			&i.Organization.Email,
			&i.Organization.Telephone,
			&i.Organization.Url,
			&i.Organization.StreetAddress,
			&i.Organization.AddressLocality,
			&i.Organization.AddressRegion,
			&i.Organization.PostalCode,
			&i.Organization.AddressCountry,
			&i.Organization.OrganizationType,
			&i.Organization.FoundingDate,
			&i.Organization.OriginNodeID,
			&i.Organization.Confidence,
			&i.Organization.CreatedAt,
			&i.Organization.UpdatedAt,
			&i.Organization.DeletedAt,
			&i.Organization.DeletionReason,
			&i.Organization.FederationUri,
			&i.Organization.NormalizedName,
			&i.Organization.MergedIntoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organizations
   SET deleted_at = now(),
       deletion_reason = $2,
       updated_at = now()
 WHERE ulid = $1
   AND deleted_at IS NULL
`

type SoftDeleteOrganizationParams struct {
	Ulid           string      `json:"ulid"`
	DeletionReason pgtype.Text `json:"deletion_reason"`
}

func (q *Queries) SoftDeleteOrganization(ctx context.Context, arg SoftDeleteOrganizationParams) error {
	_, err := q.db.Exec(ctx, softDeleteOrganization, arg.Ulid, arg.DeletionReason)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
   SET name = COALESCE($2, name),
       description = COALESCE($3, description),
       street_address = COALESCE($4, street_address),
       address_locality = COALESCE($5, address_locality),
       address_region = COALESCE($6, address_region),
       postal_code = COALESCE($7, postal_code),
       address_country = COALESCE($8, address_country),
       telephone = COALESCE($9, telephone),
       email = COALESCE($10, email),
       url = COALESCE($11, url),
       updated_at = now()
 WHERE ulid = $1
   AND deleted_at IS NULL
RETURNING organizations.id, organizations.ulid, organizations.name, organizations.legal_name, organizations.alternate_name, organizations.description, organizations.email, organizations.telephone, organizations.url, organizations.street_address, organizations.address_locality, organizations.address_region, organizations.postal_code, organizations.address_country, organizations.organization_type, organizations.founding_date, organizations.origin_node_id, organizations.confidence, organizations.created_at, organizations.updated_at, organizations.deleted_at, organizations.deletion_reason, organizations.federation_uri, organizations.normalized_name, organizations.merged_into_id
`

type UpdateOrganizationParams struct {
	Ulid            string      `json:"ulid"`
	Name            pgtype.Text `json:"name"`
	Description     pgtype.Text `json:"description"`
	StreetAddress   pgtype.Text `json:"street_address"`
	AddressLocality pgtype.Text `json:"address_locality"`
	AddressRegion   pgtype.Text `json:"address_region"`
	PostalCode      pgtype.Text `json:"postal_code"`
	AddressCountry  pgtype.Text `json:"address_country"`
	Telephone       pgtype.Text `json:"telephone"`
	Email           pgtype.Text `json:"email"`
	Url             pgtype.Text `json:"url"`
}

type UpdateOrganizationRow struct {
	Organization Organization `json:"organization"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (UpdateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.Ulid,
		arg.Name,
		arg.Description,
		arg.StreetAddress,
		arg.AddressLocality,
		arg.AddressRegion,
		arg.PostalCode,
		arg.AddressCountry,
		arg.Telephone,
		arg.Email,
		arg.Url,
	)
	var i UpdateOrganizationRow
	err := row.Scan(
		&i.Organization.ID,
		&i.Organization.Ulid,
		&i.Organization.Name,
		&i.Organization.LegalName,
		&i.Organization.AlternateName,
		&i.Organization.Description,
		&i.Organization.Email,
		&i.Organization.Telephone,
		&i.Organization.Url,
		&i.Organization.StreetAddress,
		&i.Organization.AddressLocality,
		&i.Organization.AddressRegion,
		&i.Organization.PostalCode,
		&i.Organization.AddressCountry,
		&i.Organization.OrganizationType,
		&i.Organization.FoundingDate,
		&i.Organization.OriginNodeID,
		&i.Organization.Confidence,
		&i.Organization.CreatedAt,
		&i.Organization.UpdatedAt,
		&i.Organization.DeletedAt,
		&i.Organization.DeletionReason,
		&i.Organization.FederationUri,
		&i.Organization.NormalizedName,
		&i.Organization.MergedIntoID,
	)
	return i, err
}
