// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllOrganizations = `-- name: CountAllOrganizations :one
SELECT COUNT(*) FROM organizations WHERE deleted_at IS NULL
`

func (q *Queries) CountAllOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganizationTombstone = `-- name: CreateOrganizationTombstone :exec
INSERT INTO organization_tombstones (organization_id, organization_uri, deleted_at, deletion_reason, superseded_by_uri, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOrganizationTombstoneParams struct {
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	OrganizationUri string             `json:"organization_uri"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DeletionReason  pgtype.Text        `json:"deletion_reason"`
	SupersededByUri pgtype.Text        `json:"superseded_by_uri"`
	Payload         []byte             `json:"payload"`
}

func (q *Queries) CreateOrganizationTombstone(ctx context.Context, arg CreateOrganizationTombstoneParams) error {
	_, err := q.db.Exec(ctx, createOrganizationTombstone,
		arg.OrganizationID,
		arg.OrganizationUri,
		arg.DeletedAt,
		arg.DeletionReason,
		arg.SupersededByUri,
		arg.Payload,
	)
	return err
}

const getOrganizationByULID = `-- name: GetOrganizationByULID :one
SELECT o.id,
       o.ulid,
       o.name,
       o.legal_name,
       o.description,
       o.email,
       o.telephone,
       o.url,
       o.address_locality,
       o.address_region,
       o.address_country,
       o.street_address,
       o.postal_code,
       o.organization_type,
       o.federation_uri,
       o.alternate_name,
       o.deleted_at,
       o.deletion_reason,
       o.created_at,
       o.updated_at
  FROM organizations o
 WHERE o.ulid = $1
`

type GetOrganizationByULIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	Ulid             string             `json:"ulid"`
	Name             string             `json:"name"`
	LegalName        pgtype.Text        `json:"legal_name"`
	Description      pgtype.Text        `json:"description"`
	Email            pgtype.Text        `json:"email"`
	Telephone        pgtype.Text        `json:"telephone"`
	Url              pgtype.Text        `json:"url"`
	AddressLocality  pgtype.Text        `json:"address_locality"`
	AddressRegion    pgtype.Text        `json:"address_region"`
	AddressCountry   pgtype.Text        `json:"address_country"`
	StreetAddress    pgtype.Text        `json:"street_address"`
	PostalCode       pgtype.Text        `json:"postal_code"`
	OrganizationType pgtype.Text        `json:"organization_type"`
	FederationUri    pgtype.Text        `json:"federation_uri"`
	AlternateName    pgtype.Text        `json:"alternate_name"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	DeletionReason   pgtype.Text        `json:"deletion_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrganizationByULID(ctx context.Context, ulid string) (GetOrganizationByULIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByULID, ulid)
	var i GetOrganizationByULIDRow
	err := row.Scan(
		&i.ID,
		&i.Ulid,
		&i.Name,
		&i.LegalName,
		&i.Description,
		&i.Email,
		&i.Telephone,
		&i.Url,
		&i.AddressLocality,
		&i.AddressRegion,
		&i.AddressCountry,
		&i.StreetAddress,
		&i.PostalCode,
		&i.OrganizationType,
		&i.FederationUri,
		&i.AlternateName,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationTombstoneByULID = `-- name: GetOrganizationTombstoneByULID :one
SELECT t.id,
       t.organization_id,
       t.organization_uri,
       t.deleted_at,
       t.deletion_reason,
       t.superseded_by_uri,
       t.payload
  FROM organization_tombstones t
  JOIN organizations o ON o.id = t.organization_id
 WHERE o.ulid = $1
 ORDER BY t.deleted_at DESC
 LIMIT 1
`

func (q *Queries) GetOrganizationTombstoneByULID(ctx context.Context, ulid string) (OrganizationTombstone, error) {
	row := q.db.QueryRow(ctx, getOrganizationTombstoneByULID, ulid)
	var i OrganizationTombstone
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrganizationUri,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.SupersededByUri,
		&i.Payload,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many

SELECT o.id,
       o.ulid,
       o.name,
       o.legal_name,
       o.description,
       o.email,
       o.telephone,
       o.url,
       o.address_locality,
       o.address_region,
       o.address_country,
       o.street_address,
       o.postal_code,
       o.organization_type,
       o.federation_uri,
       o.alternate_name,
       o.created_at,
       o.updated_at
  FROM organizations o
 WHERE o.deleted_at IS NULL
   AND ($1 = '' OR o.name ILIKE '%' || $1 || '%' OR o.legal_name ILIKE '%' || $1 || '%')
   AND (
     $2::timestamptz IS NULL OR
     o.created_at > $2::timestamptz OR
     (o.created_at = $2::timestamptz AND o.ulid > $3)
   )
 ORDER BY o.created_at ASC, o.ulid ASC
 LIMIT $4
`

type ListOrganizationsParams struct {
	Column1 interface{}        `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Ulid    string             `json:"ulid"`
	Limit   int32              `json:"limit"`
}

type ListOrganizationsRow struct {
	ID               pgtype.UUID        `json:"id"`
	Ulid             string             `json:"ulid"`
	Name             string             `json:"name"`
	LegalName        pgtype.Text        `json:"legal_name"`
	Description      pgtype.Text        `json:"description"`
	Email            pgtype.Text        `json:"email"`
	Telephone        pgtype.Text        `json:"telephone"`
	Url              pgtype.Text        `json:"url"`
	AddressLocality  pgtype.Text        `json:"address_locality"`
	AddressRegion    pgtype.Text        `json:"address_region"`
	AddressCountry   pgtype.Text        `json:"address_country"`
	StreetAddress    pgtype.Text        `json:"street_address"`
	PostalCode       pgtype.Text        `json:"postal_code"`
	OrganizationType pgtype.Text        `json:"organization_type"`
	FederationUri    pgtype.Text        `json:"federation_uri"`
	AlternateName    pgtype.Text        `json:"alternate_name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// SQLc queries for organizations domain.
func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizations,
		arg.Column1,
		arg.Column2,
		arg.Ulid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsRow{}
	for rows.Next() {
		var i ListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ulid,
			&i.Name,
			&i.LegalName,
			&i.Description,
			&i.Email,
			&i.Telephone,
			&i.Url,
			&i.AddressLocality,
			&i.AddressRegion,
			&i.AddressCountry,
			&i.StreetAddress,
			&i.PostalCode,
			&i.OrganizationType,
			&i.FederationUri,
			&i.AlternateName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organizations
   SET deleted_at = now(),
       deletion_reason = $2,
       updated_at = now()
 WHERE ulid = $1
   AND deleted_at IS NULL
`

type SoftDeleteOrganizationParams struct {
	Ulid           string      `json:"ulid"`
	DeletionReason pgtype.Text `json:"deletion_reason"`
}

func (q *Queries) SoftDeleteOrganization(ctx context.Context, arg SoftDeleteOrganizationParams) error {
	_, err := q.db.Exec(ctx, softDeleteOrganization, arg.Ulid, arg.DeletionReason)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
   SET name = COALESCE($2, name),
       description = COALESCE($3, description),
       street_address = COALESCE($4, street_address),
       address_locality = COALESCE($5, address_locality),
       address_region = COALESCE($6, address_region),
       postal_code = COALESCE($7, postal_code),
       address_country = COALESCE($8, address_country),
       telephone = COALESCE($9, telephone),
       email = COALESCE($10, email),
       url = COALESCE($11, url),
       updated_at = now()
 WHERE ulid = $1
   AND deleted_at IS NULL
RETURNING id, ulid, name, legal_name, description, email, telephone, url, address_locality, address_region, address_country, street_address, postal_code, organization_type, federation_uri, alternate_name, created_at, updated_at
`

type UpdateOrganizationParams struct {
	Ulid            string      `json:"ulid"`
	Name            pgtype.Text `json:"name"`
	Description     pgtype.Text `json:"description"`
	StreetAddress   pgtype.Text `json:"street_address"`
	AddressLocality pgtype.Text `json:"address_locality"`
	AddressRegion   pgtype.Text `json:"address_region"`
	PostalCode      pgtype.Text `json:"postal_code"`
	AddressCountry  pgtype.Text `json:"address_country"`
	Telephone       pgtype.Text `json:"telephone"`
	Email           pgtype.Text `json:"email"`
	Url             pgtype.Text `json:"url"`
}

type UpdateOrganizationRow struct {
	ID               pgtype.UUID        `json:"id"`
	Ulid             string             `json:"ulid"`
	Name             string             `json:"name"`
	LegalName        pgtype.Text        `json:"legal_name"`
	Description      pgtype.Text        `json:"description"`
	Email            pgtype.Text        `json:"email"`
	Telephone        pgtype.Text        `json:"telephone"`
	Url              pgtype.Text        `json:"url"`
	AddressLocality  pgtype.Text        `json:"address_locality"`
	AddressRegion    pgtype.Text        `json:"address_region"`
	AddressCountry   pgtype.Text        `json:"address_country"`
	StreetAddress    pgtype.Text        `json:"street_address"`
	PostalCode       pgtype.Text        `json:"postal_code"`
	OrganizationType pgtype.Text        `json:"organization_type"`
	FederationUri    pgtype.Text        `json:"federation_uri"`
	AlternateName    pgtype.Text        `json:"alternate_name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (UpdateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.Ulid,
		arg.Name,
		arg.Description,
		arg.StreetAddress,
		arg.AddressLocality,
		arg.AddressRegion,
		arg.PostalCode,
		arg.AddressCountry,
		arg.Telephone,
		arg.Email,
		arg.Url,
	)
	var i UpdateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Ulid,
		&i.Name,
		&i.LegalName,
		&i.Description,
		&i.Email,
		&i.Telephone,
		&i.Url,
		&i.AddressLocality,
		&i.AddressRegion,
		&i.AddressCountry,
		&i.StreetAddress,
		&i.PostalCode,
		&i.OrganizationType,
		&i.FederationUri,
		&i.AlternateName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
