// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: places.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlaceByULID = `-- name: GetPlaceByULID :one
SELECT p.id,
       p.ulid,
       p.name,
       p.description,
       p.address_locality,
       p.address_region,
       p.address_country,
       p.created_at,
       p.updated_at
  FROM places p
 WHERE p.ulid = $1
`

type GetPlaceByULIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	Ulid            string             `json:"ulid"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	AddressLocality pgtype.Text        `json:"address_locality"`
	AddressRegion   pgtype.Text        `json:"address_region"`
	AddressCountry  pgtype.Text        `json:"address_country"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPlaceByULID(ctx context.Context, ulid string) (GetPlaceByULIDRow, error) {
	row := q.db.QueryRow(ctx, getPlaceByULID, ulid)
	var i GetPlaceByULIDRow
	err := row.Scan(
		&i.ID,
		&i.Ulid,
		&i.Name,
		&i.Description,
		&i.AddressLocality,
		&i.AddressRegion,
		&i.AddressCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlaces = `-- name: ListPlaces :many

SELECT p.id,
       p.ulid,
       p.name,
       p.description,
       p.address_locality,
       p.address_region,
       p.address_country,
       p.created_at,
       p.updated_at
  FROM places p
 WHERE ($1 = '' OR p.address_locality ILIKE '%' || $1 || '%')
   AND ($2 = '' OR p.name ILIKE '%' || $2 || '%' OR p.description ILIKE '%' || $2 || '%')
   AND (
     $3::timestamptz IS NULL OR
     p.created_at > $3::timestamptz OR
     (p.created_at = $3::timestamptz AND p.ulid > $4)
   )
 ORDER BY p.created_at ASC, p.ulid ASC
 LIMIT $5
`

type ListPlacesParams struct {
	Column1 interface{}        `json:"column_1"`
	Column2 interface{}        `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Ulid    string             `json:"ulid"`
	Limit   int32              `json:"limit"`
}

type ListPlacesRow struct {
	ID              pgtype.UUID        `json:"id"`
	Ulid            string             `json:"ulid"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	AddressLocality pgtype.Text        `json:"address_locality"`
	AddressRegion   pgtype.Text        `json:"address_region"`
	AddressCountry  pgtype.Text        `json:"address_country"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// SQLc queries for places domain.
func (q *Queries) ListPlaces(ctx context.Context, arg ListPlacesParams) ([]ListPlacesRow, error) {
	rows, err := q.db.Query(ctx, listPlaces,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Ulid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacesRow{}
	for rows.Next() {
		var i ListPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Ulid,
			&i.Name,
			&i.Description,
			&i.AddressLocality,
			&i.AddressRegion,
			&i.AddressCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
