// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: places.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllPlaces = `-- name: CountAllPlaces :one
SELECT COUNT(*) FROM places WHERE deleted_at IS NULL
`

func (q *Queries) CountAllPlaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllPlaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaceTombstone = `-- name: CreatePlaceTombstone :exec
INSERT INTO place_tombstones (place_id, place_uri, deleted_at, deletion_reason, superseded_by_uri, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePlaceTombstoneParams struct {
	PlaceID         pgtype.UUID        `json:"place_id"`
	PlaceUri        string             `json:"place_uri"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DeletionReason  pgtype.Text        `json:"deletion_reason"`
	SupersededByUri pgtype.Text        `json:"superseded_by_uri"`
	Payload         []byte             `json:"payload"`
}

func (q *Queries) CreatePlaceTombstone(ctx context.Context, arg CreatePlaceTombstoneParams) error {
	_, err := q.db.Exec(ctx, createPlaceTombstone,
		arg.PlaceID,
		arg.PlaceUri,
		arg.DeletedAt,
		arg.DeletionReason,
		arg.SupersededByUri,
		arg.Payload,
	)
	return err
}

const getPlaceByULID = `-- name: GetPlaceByULID :one
SELECT p.id,
       p.ulid,
       p.name,
       p.description,
       p.street_address,
       p.address_locality,
       p.address_region,
       p.postal_code,
       p.address_country,
       p.latitude,
       p.longitude,
       p.telephone,
       p.email,
       p.url,
       p.maximum_attendee_capacity,
       p.venue_type,
       p.federation_uri,
       p.deleted_at,
       p.deletion_reason,
       p.created_at,
       p.updated_at
  FROM places p
 WHERE p.ulid = $1
`

type GetPlaceByULIDRow struct {
	ID                      pgtype.UUID        `json:"id"`
	Ulid                    string             `json:"ulid"`
	Name                    string             `json:"name"`
	Description             pgtype.Text        `json:"description"`
	StreetAddress           pgtype.Text        `json:"street_address"`
	AddressLocality         pgtype.Text        `json:"address_locality"`
	AddressRegion           pgtype.Text        `json:"address_region"`
	PostalCode              pgtype.Text        `json:"postal_code"`
	AddressCountry          pgtype.Text        `json:"address_country"`
	Latitude                pgtype.Numeric     `json:"latitude"`
	Longitude               pgtype.Numeric     `json:"longitude"`
	Telephone               pgtype.Text        `json:"telephone"`
	Email                   pgtype.Text        `json:"email"`
	Url                     pgtype.Text        `json:"url"`
	MaximumAttendeeCapacity pgtype.Int4        `json:"maximum_attendee_capacity"`
	VenueType               pgtype.Text        `json:"venue_type"`
	FederationUri           pgtype.Text        `json:"federation_uri"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	DeletionReason          pgtype.Text        `json:"deletion_reason"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPlaceByULID(ctx context.Context, ulid string) (GetPlaceByULIDRow, error) {
	row := q.db.QueryRow(ctx, getPlaceByULID, ulid)
	var i GetPlaceByULIDRow
	err := row.Scan(
		&i.ID,
		&i.Ulid,
		&i.Name,
		&i.Description,
		&i.StreetAddress,
		&i.AddressLocality,
		&i.AddressRegion,
		&i.PostalCode,
		&i.AddressCountry,
		&i.Latitude,
		&i.Longitude,
		&i.Telephone,
		&i.Email,
		&i.Url,
		&i.MaximumAttendeeCapacity,
		&i.VenueType,
		&i.FederationUri,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaceTombstoneByULID = `-- name: GetPlaceTombstoneByULID :one
SELECT t.id,
       t.place_id,
       t.place_uri,
       t.deleted_at,
       t.deletion_reason,
       t.superseded_by_uri,
       t.payload
  FROM place_tombstones t
  JOIN places p ON p.id = t.place_id
 WHERE p.ulid = $1
 ORDER BY t.deleted_at DESC
 LIMIT 1
`

func (q *Queries) GetPlaceTombstoneByULID(ctx context.Context, ulid string) (PlaceTombstone, error) {
	row := q.db.QueryRow(ctx, getPlaceTombstoneByULID, ulid)
	var i PlaceTombstone
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.PlaceUri,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.SupersededByUri,
		&i.Payload,
	)
	return i, err
}

const listPlacesByCreatedAt = `-- name: ListPlacesByCreatedAt :many

SELECT p.id,
       p.ulid,
       p.name,
       p.description,
       p.street_address,
       p.address_locality,
       p.address_region,
       p.postal_code,
       p.address_country,
       p.latitude,
       p.longitude,
       p.telephone,
       p.email,
       p.url,
       p.maximum_attendee_capacity,
       p.venue_type,
       p.federation_uri,
       p.created_at,
       p.updated_at
  FROM places p
 WHERE p.deleted_at IS NULL
   AND ($1::text IS NULL OR p.address_locality ILIKE '%' || $1 || '%')
   AND ($2::text IS NULL OR p.name ILIKE '%' || $2 || '%' OR p.description ILIKE '%' || $2 || '%')
   AND (
     $3::timestamptz IS NULL OR
     p.created_at > $3::timestamptz OR
     (p.created_at = $3::timestamptz AND p.ulid > $4)
   )
 ORDER BY p.created_at ASC, p.ulid ASC
 LIMIT $5
`

type ListPlacesByCreatedAtParams struct {
	City            pgtype.Text        `json:"city"`
	Query           pgtype.Text        `json:"query"`
	CursorTimestamp pgtype.Timestamptz `json:"cursor_timestamp"`
	CursorUlid      pgtype.Text        `json:"cursor_ulid"`
	Limit           int32              `json:"limit"`
}

type ListPlacesByCreatedAtRow struct {
	ID                      pgtype.UUID        `json:"id"`
	Ulid                    string             `json:"ulid"`
	Name                    string             `json:"name"`
	Description             pgtype.Text        `json:"description"`
	StreetAddress           pgtype.Text        `json:"street_address"`
	AddressLocality         pgtype.Text        `json:"address_locality"`
	AddressRegion           pgtype.Text        `json:"address_region"`
	PostalCode              pgtype.Text        `json:"postal_code"`
	AddressCountry          pgtype.Text        `json:"address_country"`
	Latitude                pgtype.Numeric     `json:"latitude"`
	Longitude               pgtype.Numeric     `json:"longitude"`
	Telephone               pgtype.Text        `json:"telephone"`
	Email                   pgtype.Text        `json:"email"`
	Url                     pgtype.Text        `json:"url"`
	MaximumAttendeeCapacity pgtype.Int4        `json:"maximum_attendee_capacity"`
	VenueType               pgtype.Text        `json:"venue_type"`
	FederationUri           pgtype.Text        `json:"federation_uri"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

// SQLc queries for places domain.
func (q *Queries) ListPlacesByCreatedAt(ctx context.Context, arg ListPlacesByCreatedAtParams) ([]ListPlacesByCreatedAtRow, error) {
	rows, err := q.db.Query(ctx, listPlacesByCreatedAt,
		arg.City,
		arg.Query,
		arg.CursorTimestamp,
		arg.CursorUlid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacesByCreatedAtRow{}
	for rows.Next() {
		var i ListPlacesByCreatedAtRow
		if err := rows.Scan(
			&i.ID,
			&i.Ulid,
			&i.Name,
			&i.Description,
			&i.StreetAddress,
			&i.AddressLocality,
			&i.AddressRegion,
			&i.PostalCode,
			&i.AddressCountry,
			&i.Latitude,
			&i.Longitude,
			&i.Telephone,
			&i.Email,
			&i.Url,
			&i.MaximumAttendeeCapacity,
			&i.VenueType,
			&i.FederationUri,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesByCreatedAtDesc = `-- name: ListPlacesByCreatedAtDesc :many
SELECT p.id,
       p.ulid,
       p.name,
       p.description,
       p.street_address,
       p.address_locality,
       p.address_region,
       p.postal_code,
       p.address_country,
       p.latitude,
       p.longitude,
       p.telephone,
       p.email,
       p.url,
       p.maximum_attendee_capacity,
       p.venue_type,
       p.federation_uri,
       p.created_at,
       p.updated_at
  FROM places p
 WHERE p.deleted_at IS NULL
   AND ($1::text IS NULL OR p.address_locality ILIKE '%' || $1 || '%')
   AND ($2::text IS NULL OR p.name ILIKE '%' || $2 || '%' OR p.description ILIKE '%' || $2 || '%')
   AND (
     $3::timestamptz IS NULL OR
     p.created_at < $3::timestamptz OR
     (p.created_at = $3::timestamptz AND p.ulid > $4)
   )
 ORDER BY p.created_at DESC, p.ulid ASC
 LIMIT $5
`

type ListPlacesByCreatedAtDescParams struct {
	City            pgtype.Text        `json:"city"`
	Query           pgtype.Text        `json:"query"`
	CursorTimestamp pgtype.Timestamptz `json:"cursor_timestamp"`
	CursorUlid      pgtype.Text        `json:"cursor_ulid"`
	Limit           int32              `json:"limit"`
}

type ListPlacesByCreatedAtDescRow struct {
	ID                      pgtype.UUID        `json:"id"`
	Ulid                    string             `json:"ulid"`
	Name                    string             `json:"name"`
	Description             pgtype.Text        `json:"description"`
	StreetAddress           pgtype.Text        `json:"street_address"`
	AddressLocality         pgtype.Text        `json:"address_locality"`
	AddressRegion           pgtype.Text        `json:"address_region"`
	PostalCode              pgtype.Text        `json:"postal_code"`
	AddressCountry          pgtype.Text        `json:"address_country"`
	Latitude                pgtype.Numeric     `json:"latitude"`
	Longitude               pgtype.Numeric     `json:"longitude"`
	Telephone               pgtype.Text        `json:"telephone"`
	Email                   pgtype.Text        `json:"email"`
	Url                     pgtype.Text        `json:"url"`
	MaximumAttendeeCapacity pgtype.Int4        `json:"maximum_attendee_capacity"`
	VenueType               pgtype.Text        `json:"venue_type"`
	FederationUri           pgtype.Text        `json:"federation_uri"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPlacesByCreatedAtDesc(ctx context.Context, arg ListPlacesByCreatedAtDescParams) ([]ListPlacesByCreatedAtDescRow, error) {
	rows, err := q.db.Query(ctx, listPlacesByCreatedAtDesc,
		arg.City,
		arg.Query,
		arg.CursorTimestamp,
		arg.CursorUlid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacesByCreatedAtDescRow{}
	for rows.Next() {
		var i ListPlacesByCreatedAtDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Ulid,
			&i.Name,
			&i.Description,
			&i.StreetAddress,
			&i.AddressLocality,
			&i.AddressRegion,
			&i.PostalCode,
			&i.AddressCountry,
			&i.Latitude,
			&i.Longitude,
			&i.Telephone,
			&i.Email,
			&i.Url,
			&i.MaximumAttendeeCapacity,
			&i.VenueType,
			&i.FederationUri,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesByName = `-- name: ListPlacesByName :many
SELECT p.id,
       p.ulid,
       p.name,
       p.description,
       p.street_address,
       p.address_locality,
       p.address_region,
       p.postal_code,
       p.address_country,
       p.latitude,
       p.longitude,
       p.telephone,
       p.email,
       p.url,
       p.maximum_attendee_capacity,
       p.venue_type,
       p.federation_uri,
       p.created_at,
       p.updated_at
  FROM places p
 WHERE p.deleted_at IS NULL
   AND ($1::text IS NULL OR p.address_locality ILIKE '%' || $1 || '%')
   AND ($2::text IS NULL OR p.name ILIKE '%' || $2 || '%' OR p.description ILIKE '%' || $2 || '%')
   AND (
     $3::text IS NULL OR
     p.name > $3 OR
     (p.name = $3 AND p.ulid > $4)
   )
 ORDER BY p.name ASC, p.ulid ASC
 LIMIT $5
`

type ListPlacesByNameParams struct {
	City       pgtype.Text `json:"city"`
	Query      pgtype.Text `json:"query"`
	CursorName pgtype.Text `json:"cursor_name"`
	CursorUlid pgtype.Text `json:"cursor_ulid"`
	Limit      int32       `json:"limit"`
}

type ListPlacesByNameRow struct {
	ID                      pgtype.UUID        `json:"id"`
	Ulid                    string             `json:"ulid"`
	Name                    string             `json:"name"`
	Description             pgtype.Text        `json:"description"`
	StreetAddress           pgtype.Text        `json:"street_address"`
	AddressLocality         pgtype.Text        `json:"address_locality"`
	AddressRegion           pgtype.Text        `json:"address_region"`
	PostalCode              pgtype.Text        `json:"postal_code"`
	AddressCountry          pgtype.Text        `json:"address_country"`
	Latitude                pgtype.Numeric     `json:"latitude"`
	Longitude               pgtype.Numeric     `json:"longitude"`
	Telephone               pgtype.Text        `json:"telephone"`
	Email                   pgtype.Text        `json:"email"`
	Url                     pgtype.Text        `json:"url"`
	MaximumAttendeeCapacity pgtype.Int4        `json:"maximum_attendee_capacity"`
	VenueType               pgtype.Text        `json:"venue_type"`
	FederationUri           pgtype.Text        `json:"federation_uri"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPlacesByName(ctx context.Context, arg ListPlacesByNameParams) ([]ListPlacesByNameRow, error) {
	rows, err := q.db.Query(ctx, listPlacesByName,
		arg.City,
		arg.Query,
		arg.CursorName,
		arg.CursorUlid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacesByNameRow{}
	for rows.Next() {
		var i ListPlacesByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Ulid,
			&i.Name,
			&i.Description,
			&i.StreetAddress,
			&i.AddressLocality,
			&i.AddressRegion,
			&i.PostalCode,
			&i.AddressCountry,
			&i.Latitude,
			&i.Longitude,
			&i.Telephone,
			&i.Email,
			&i.Url,
			&i.MaximumAttendeeCapacity,
			&i.VenueType,
			&i.FederationUri,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesByNameDesc = `-- name: ListPlacesByNameDesc :many
SELECT p.id,
       p.ulid,
       p.name,
       p.description,
       p.street_address,
       p.address_locality,
       p.address_region,
       p.postal_code,
       p.address_country,
       p.latitude,
       p.longitude,
       p.telephone,
       p.email,
       p.url,
       p.maximum_attendee_capacity,
       p.venue_type,
       p.federation_uri,
       p.created_at,
       p.updated_at
  FROM places p
 WHERE p.deleted_at IS NULL
   AND ($1::text IS NULL OR p.address_locality ILIKE '%' || $1 || '%')
   AND ($2::text IS NULL OR p.name ILIKE '%' || $2 || '%' OR p.description ILIKE '%' || $2 || '%')
   AND (
     $3::text IS NULL OR
     p.name < $3 OR
     (p.name = $3 AND p.ulid > $4)
   )
 ORDER BY p.name DESC, p.ulid ASC
 LIMIT $5
`

type ListPlacesByNameDescParams struct {
	City       pgtype.Text `json:"city"`
	Query      pgtype.Text `json:"query"`
	CursorName pgtype.Text `json:"cursor_name"`
	CursorUlid pgtype.Text `json:"cursor_ulid"`
	Limit      int32       `json:"limit"`
}

type ListPlacesByNameDescRow struct {
	ID                      pgtype.UUID        `json:"id"`
	Ulid                    string             `json:"ulid"`
	Name                    string             `json:"name"`
	Description             pgtype.Text        `json:"description"`
	StreetAddress           pgtype.Text        `json:"street_address"`
	AddressLocality         pgtype.Text        `json:"address_locality"`
	AddressRegion           pgtype.Text        `json:"address_region"`
	PostalCode              pgtype.Text        `json:"postal_code"`
	AddressCountry          pgtype.Text        `json:"address_country"`
	Latitude                pgtype.Numeric     `json:"latitude"`
	Longitude               pgtype.Numeric     `json:"longitude"`
	Telephone               pgtype.Text        `json:"telephone"`
	Email                   pgtype.Text        `json:"email"`
	Url                     pgtype.Text        `json:"url"`
	MaximumAttendeeCapacity pgtype.Int4        `json:"maximum_attendee_capacity"`
	VenueType               pgtype.Text        `json:"venue_type"`
	FederationUri           pgtype.Text        `json:"federation_uri"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPlacesByNameDesc(ctx context.Context, arg ListPlacesByNameDescParams) ([]ListPlacesByNameDescRow, error) {
	rows, err := q.db.Query(ctx, listPlacesByNameDesc,
		arg.City,
		arg.Query,
		arg.CursorName,
		arg.CursorUlid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacesByNameDescRow{}
	for rows.Next() {
		var i ListPlacesByNameDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Ulid,
			&i.Name,
			&i.Description,
			&i.StreetAddress,
			&i.AddressLocality,
			&i.AddressRegion,
			&i.PostalCode,
			&i.AddressCountry,
			&i.Latitude,
			&i.Longitude,
			&i.Telephone,
			&i.Email,
			&i.Url,
			&i.MaximumAttendeeCapacity,
			&i.VenueType,
			&i.FederationUri,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePlace = `-- name: SoftDeletePlace :exec
UPDATE places
   SET deleted_at = now(),
       deletion_reason = $2,
       updated_at = now()
 WHERE ulid = $1
   AND deleted_at IS NULL
`

type SoftDeletePlaceParams struct {
	Ulid           string      `json:"ulid"`
	DeletionReason pgtype.Text `json:"deletion_reason"`
}

func (q *Queries) SoftDeletePlace(ctx context.Context, arg SoftDeletePlaceParams) error {
	_, err := q.db.Exec(ctx, softDeletePlace, arg.Ulid, arg.DeletionReason)
	return err
}

const updatePlace = `-- name: UpdatePlace :one
UPDATE places
   SET name = COALESCE($2, name),
       description = COALESCE($3, description),
       street_address = COALESCE($4, street_address),
       address_locality = COALESCE($5, address_locality),
       address_region = COALESCE($6, address_region),
       postal_code = COALESCE($7, postal_code),
       address_country = COALESCE($8, address_country),
       telephone = COALESCE($9, telephone),
       email = COALESCE($10, email),
       url = COALESCE($11, url),
       updated_at = now()
 WHERE ulid = $1
   AND deleted_at IS NULL
RETURNING id, ulid, name, description, street_address, address_locality, address_region, postal_code, address_country, latitude, longitude, telephone, email, url, maximum_attendee_capacity, venue_type, federation_uri, created_at, updated_at
`

type UpdatePlaceParams struct {
	Ulid            string      `json:"ulid"`
	Name            pgtype.Text `json:"name"`
	Description     pgtype.Text `json:"description"`
	StreetAddress   pgtype.Text `json:"street_address"`
	AddressLocality pgtype.Text `json:"address_locality"`
	AddressRegion   pgtype.Text `json:"address_region"`
	PostalCode      pgtype.Text `json:"postal_code"`
	AddressCountry  pgtype.Text `json:"address_country"`
	Telephone       pgtype.Text `json:"telephone"`
	Email           pgtype.Text `json:"email"`
	Url             pgtype.Text `json:"url"`
}

type UpdatePlaceRow struct {
	ID                      pgtype.UUID        `json:"id"`
	Ulid                    string             `json:"ulid"`
	Name                    string             `json:"name"`
	Description             pgtype.Text        `json:"description"`
	StreetAddress           pgtype.Text        `json:"street_address"`
	AddressLocality         pgtype.Text        `json:"address_locality"`
	AddressRegion           pgtype.Text        `json:"address_region"`
	PostalCode              pgtype.Text        `json:"postal_code"`
	AddressCountry          pgtype.Text        `json:"address_country"`
	Latitude                pgtype.Numeric     `json:"latitude"`
	Longitude               pgtype.Numeric     `json:"longitude"`
	Telephone               pgtype.Text        `json:"telephone"`
	Email                   pgtype.Text        `json:"email"`
	Url                     pgtype.Text        `json:"url"`
	MaximumAttendeeCapacity pgtype.Int4        `json:"maximum_attendee_capacity"`
	VenueType               pgtype.Text        `json:"venue_type"`
	FederationUri           pgtype.Text        `json:"federation_uri"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (UpdatePlaceRow, error) {
	row := q.db.QueryRow(ctx, updatePlace,
		arg.Ulid,
		arg.Name,
		arg.Description,
		arg.StreetAddress,
		arg.AddressLocality,
		arg.AddressRegion,
		arg.PostalCode,
		arg.AddressCountry,
		arg.Telephone,
		arg.Email,
		arg.Url,
	)
	var i UpdatePlaceRow
	err := row.Scan(
		&i.ID,
		&i.Ulid,
		&i.Name,
		&i.Description,
		&i.StreetAddress,
		&i.AddressLocality,
		&i.AddressRegion,
		&i.PostalCode,
		&i.AddressCountry,
		&i.Latitude,
		&i.Longitude,
		&i.Telephone,
		&i.Email,
		&i.Url,
		&i.MaximumAttendeeCapacity,
		&i.VenueType,
		&i.FederationUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
