// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateBatchIngestionResult(ctx context.Context, arg CreateBatchIngestionResultParams) error
	CreateEventTombstone(ctx context.Context, arg CreateEventTombstoneParams) error
	CreateFederatedEventOccurrence(ctx context.Context, arg CreateFederatedEventOccurrenceParams) error
	// SQLc queries for federation sync.
	CreateFederationNode(ctx context.Context, arg CreateFederationNodeParams) (FederationNode, error)
	CreateOrganizationTombstone(ctx context.Context, arg CreateOrganizationTombstoneParams) error
	CreatePlaceTombstone(ctx context.Context, arg CreatePlaceTombstoneParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeactivateAPIKey(ctx context.Context, id pgtype.UUID) error
	DeleteFederationNode(ctx context.Context, id pgtype.UUID) error
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error)
	// Gets complete provenance history for a field, including superseded records
	GetAllFieldProvenanceHistory(ctx context.Context, arg GetAllFieldProvenanceHistoryParams) ([]GetAllFieldProvenanceHistoryRow, error)
	// SQLc queries for batch ingestion operations.
	GetBatchIngestionResult(ctx context.Context, batchID string) (BatchIngestionResult, error)
	// Gets the canonical (winning) field value based on conflict resolution rules
	// Priority: trust_level DESC, confidence DESC, observed_at DESC
	GetCanonicalFieldValue(ctx context.Context, arg GetCanonicalFieldValueParams) (GetCanonicalFieldValueRow, error)
	// Federation Sync Queries
	GetEventByFederationURI(ctx context.Context, federationUri pgtype.Text) (Event, error)
	GetEventByULID(ctx context.Context, ulid string) ([]GetEventByULIDRow, error)
	GetEventChangeByID(ctx context.Context, id pgtype.UUID) (GetEventChangeByIDRow, error)
	// SQLc queries for provenance tracking.
	// Retrieves all sources for a given event with source metadata and timestamps (FR-029)
	GetEventSources(ctx context.Context, eventID pgtype.UUID) ([]GetEventSourcesRow, error)
	GetEventTombstoneByEventID(ctx context.Context, eventID pgtype.UUID) (EventTombstone, error)
	GetEventTombstoneByEventULID(ctx context.Context, ulid string) (EventTombstone, error)
	GetEventTombstoneByURI(ctx context.Context, eventUri string) (EventTombstone, error)
	GetFederationNodeByDomain(ctx context.Context, nodeDomain string) (FederationNode, error)
	GetFederationNodeByID(ctx context.Context, id pgtype.UUID) (FederationNode, error)
	// Retrieves field-level provenance for an event, optionally filtered by field paths
	// Includes source metadata and timestamps per FR-024 and FR-029
	GetFieldProvenance(ctx context.Context, eventID pgtype.UUID) ([]GetFieldProvenanceRow, error)
	// Retrieves field-level provenance for specific field paths on an event
	GetFieldProvenanceForPaths(ctx context.Context, arg GetFieldProvenanceForPathsParams) ([]GetFieldProvenanceForPathsRow, error)
	GetIdempotencyKey(ctx context.Context, key string) (GetIdempotencyKeyRow, error)
	GetLatestEventChange(ctx context.Context) (GetLatestEventChangeRow, error)
	GetOrganizationByULID(ctx context.Context, ulid string) (GetOrganizationByULIDRow, error)
	GetOrganizationTombstoneByULID(ctx context.Context, ulid string) (OrganizationTombstone, error)
	GetPlaceByULID(ctx context.Context, ulid string) (GetPlaceByULIDRow, error)
	GetPlaceTombstoneByULID(ctx context.Context, ulid string) (PlaceTombstone, error)
	// Retrieves source metadata by ID
	GetSourceByID(ctx context.Context, id pgtype.UUID) (GetSourceByIDRow, error)
	// Gets all sources that contributed to an event (deduplicated)
	GetSourcesByEventID(ctx context.Context, eventID pgtype.UUID) ([]GetSourcesByEventIDRow, error)
	// SQLc queries for authentication.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Records a source's contribution to an event with source and received timestamps (FR-029)
	InsertEventSource(ctx context.Context, arg InsertEventSourceParams) (EventSource, error)
	// Records field-level provenance with source timestamp
	InsertFieldProvenance(ctx context.Context, arg InsertFieldProvenanceParams) (FieldProvenance, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (InsertIdempotencyKeyRow, error)
	ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error)
	// SQLc queries for change feeds.
	ListEventChanges(ctx context.Context, arg ListEventChangesParams) ([]ListEventChangesRow, error)
	ListEventTombstones(ctx context.Context, arg ListEventTombstonesParams) ([]EventTombstone, error)
	ListFederationNodes(ctx context.Context, arg ListFederationNodesParams) ([]FederationNode, error)
	// SQLc queries for organizations domain.
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error)
	// SQLc queries for places domain.
	ListPlaces(ctx context.Context, arg ListPlacesParams) ([]ListPlacesRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	MergeEventIntoDuplicate(ctx context.Context, arg MergeEventIntoDuplicateParams) error
	SoftDeleteEvent(ctx context.Context, arg SoftDeleteEventParams) error
	SoftDeleteOrganization(ctx context.Context, arg SoftDeleteOrganizationParams) error
	SoftDeletePlace(ctx context.Context, arg SoftDeletePlaceParams) error
	// Marks a field provenance record as superseded by a new record
	SupersedeFieldProvenance(ctx context.Context, arg SupersedeFieldProvenanceParams) error
	UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error)
	UpdateFederationNode(ctx context.Context, arg UpdateFederationNodeParams) (FederationNode, error)
	UpdateFederationNodeHealth(ctx context.Context, arg UpdateFederationNodeHealthParams) error
	UpdateFederationNodeSyncStatus(ctx context.Context, arg UpdateFederationNodeSyncStatusParams) error
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertFederatedEvent(ctx context.Context, arg UpsertFederatedEventParams) (Event, error)
}

var _ Querier = (*Queries)(nil)
