// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptDeveloperInvitation(ctx context.Context, id pgtype.UUID) error
	ActivateUser(ctx context.Context, id pgtype.UUID) error
	// Mark review as approved
	ApproveReview(ctx context.Context, arg ApproveReviewParams) (EventReviewQueue, error)
	// Archive old approved/superseded/merged reviews (90 day retention)
	CleanupArchivedReviews(ctx context.Context) error
	// Delete rejected reviews for past events (7 day grace period)
	CleanupExpiredRejections(ctx context.Context) error
	// Delete pending reviews for events that have already started (too late to review)
	CleanupUnreviewedEvents(ctx context.Context) error
	CountAllEvents(ctx context.Context) (int64, error)
	CountAllOrganizations(ctx context.Context) (int64, error)
	CountAllPlaces(ctx context.Context) (int64, error)
	// SQLc queries for sources registry.
	CountAllSources(ctx context.Context) (int64, error)
	CountAllUsers(ctx context.Context) (int64, error)
	CountDeveloperAPIKeys(ctx context.Context, developerID pgtype.UUID) (int64, error)
	CountDevelopers(ctx context.Context) (int64, error)
	CountEventsByLifecycleState(ctx context.Context, lifecycleState string) (int64, error)
	CountEventsCreatedSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	CountPastEvents(ctx context.Context) (int64, error)
	// Count total reviews by status (for badge display)
	CountReviewQueueByStatus(ctx context.Context, status pgtype.Text) (int64, error)
	CountUpcomingEvents(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateBatchIngestionResult(ctx context.Context, arg CreateBatchIngestionResultParams) error
	// SQLc queries for developer management and invitations.
	// Developer CRUD operations
	CreateDeveloper(ctx context.Context, arg CreateDeveloperParams) (Developer, error)
	CreateDeveloperAPIKey(ctx context.Context, arg CreateDeveloperAPIKeyParams) (CreateDeveloperAPIKeyRow, error)
	// Developer invitation operations
	CreateDeveloperInvitation(ctx context.Context, arg CreateDeveloperInvitationParams) (DeveloperInvitation, error)
	CreateEventTombstone(ctx context.Context, arg CreateEventTombstoneParams) error
	CreateFederatedEventOccurrence(ctx context.Context, arg CreateFederatedEventOccurrenceParams) error
	// SQLc queries for federation sync.
	CreateFederationNode(ctx context.Context, arg CreateFederationNodeParams) (FederationNode, error)
	CreateOrganizationTombstone(ctx context.Context, arg CreateOrganizationTombstoneParams) error
	CreatePlaceTombstone(ctx context.Context, arg CreatePlaceTombstoneParams) error
	// Create new review queue entry
	CreateReviewQueueEntry(ctx context.Context, arg CreateReviewQueueEntryParams) (EventReviewQueue, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// User Invitation Queries
	CreateUserInvitation(ctx context.Context, arg CreateUserInvitationParams) (CreateUserInvitationRow, error)
	DeactivateAPIKey(ctx context.Context, id pgtype.UUID) error
	DeactivateDeveloper(ctx context.Context, id pgtype.UUID) error
	// User Management Queries
	DeactivateUser(ctx context.Context, id pgtype.UUID) error
	DeleteFederationNode(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	// SQLc queries for event_review_queue domain.
	// See docs/architecture/event-review-workflow.md for complete design.
	// Find existing review by deduplication keys (checks source_external_id or dedup_hash)
	FindReviewByDedup(ctx context.Context, arg FindReviewByDedupParams) (FindReviewByDedupRow, error)
	GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error)
	GetAPIKeyUsage(ctx context.Context, arg GetAPIKeyUsageParams) ([]ApiKeyUsage, error)
	GetAPIKeyUsageTotal(ctx context.Context, arg GetAPIKeyUsageTotalParams) (GetAPIKeyUsageTotalRow, error)
	// Gets complete provenance history for a field, including superseded records
	GetAllFieldProvenanceHistory(ctx context.Context, arg GetAllFieldProvenanceHistoryParams) ([]GetAllFieldProvenanceHistoryRow, error)
	// SQLc queries for batch ingestion operations.
	GetBatchIngestionResult(ctx context.Context, batchID string) (BatchIngestionResult, error)
	// Gets the canonical (winning) field value based on conflict resolution rules
	// Priority: trust_level DESC, confidence DESC, observed_at DESC
	GetCanonicalFieldValue(ctx context.Context, arg GetCanonicalFieldValueParams) (GetCanonicalFieldValueRow, error)
	GetDeveloperByEmail(ctx context.Context, email string) (Developer, error)
	GetDeveloperByGitHubID(ctx context.Context, githubID pgtype.Int8) (Developer, error)
	GetDeveloperByID(ctx context.Context, id pgtype.UUID) (Developer, error)
	GetDeveloperInvitationByTokenHash(ctx context.Context, tokenHash string) (DeveloperInvitation, error)
	GetDeveloperUsageTotal(ctx context.Context, arg GetDeveloperUsageTotalParams) (GetDeveloperUsageTotalRow, error)
	// Federation Sync Queries
	GetEventByFederationURI(ctx context.Context, federationUri pgtype.Text) (Event, error)
	// SQLc queries for events domain.
	GetEventByULID(ctx context.Context, ulid string) ([]GetEventByULIDRow, error)
	GetEventChangeByID(ctx context.Context, id pgtype.UUID) (GetEventChangeByIDRow, error)
	GetEventDateRange(ctx context.Context) (GetEventDateRangeRow, error)
	// SQLc queries for provenance tracking.
	// Retrieves all sources for a given event with source metadata and timestamps (FR-029)
	GetEventSources(ctx context.Context, eventID pgtype.UUID) ([]GetEventSourcesRow, error)
	GetEventTombstoneByEventID(ctx context.Context, eventID pgtype.UUID) (EventTombstone, error)
	GetEventTombstoneByEventULID(ctx context.Context, ulid string) (EventTombstone, error)
	GetEventTombstoneByURI(ctx context.Context, eventUri string) (EventTombstone, error)
	GetFederationNodeByDomain(ctx context.Context, nodeDomain string) (FederationNode, error)
	GetFederationNodeByID(ctx context.Context, id pgtype.UUID) (FederationNode, error)
	// Retrieves field-level provenance for an event, optionally filtered by field paths
	// Includes source metadata and timestamps per FR-024 and FR-029
	GetFieldProvenance(ctx context.Context, eventID pgtype.UUID) ([]GetFieldProvenanceRow, error)
	// Retrieves field-level provenance for specific field paths on an event
	GetFieldProvenanceForPaths(ctx context.Context, arg GetFieldProvenanceForPathsParams) ([]GetFieldProvenanceForPathsRow, error)
	GetIdempotencyKey(ctx context.Context, key string) (GetIdempotencyKeyRow, error)
	GetLatestEventChange(ctx context.Context) (GetLatestEventChangeRow, error)
	GetOrganizationByULID(ctx context.Context, ulid string) (GetOrganizationByULIDRow, error)
	GetOrganizationTombstoneByULID(ctx context.Context, ulid string) (OrganizationTombstone, error)
	GetPlaceByULID(ctx context.Context, ulid string) (GetPlaceByULIDRow, error)
	GetPlaceTombstoneByULID(ctx context.Context, ulid string) (PlaceTombstone, error)
	// Get single review by ID
	GetReviewQueueEntry(ctx context.Context, id int32) (GetReviewQueueEntryRow, error)
	// Retrieves source metadata by ID
	GetSourceByID(ctx context.Context, id pgtype.UUID) (GetSourceByIDRow, error)
	// Gets all sources that contributed to an event (deduplicated)
	GetSourcesByEventID(ctx context.Context, eventID pgtype.UUID) ([]GetSourcesByEventIDRow, error)
	// SQLc queries for authentication.
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserInvitationByTokenHash(ctx context.Context, tokenHash string) (UserInvitation, error)
	// Records a source's contribution to an event with source and received timestamps (FR-029)
	InsertEventSource(ctx context.Context, arg InsertEventSourceParams) (EventSource, error)
	// Records field-level provenance with source timestamp
	InsertFieldProvenance(ctx context.Context, arg InsertFieldProvenanceParams) (FieldProvenance, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (InsertIdempotencyKeyRow, error)
	// SQLc queries for event_not_duplicates table.
	// Tracks pairs of events that an admin has confirmed are NOT duplicates,
	// preventing them from being re-flagged during near-duplicate detection.
	// Record that two events are confirmed as NOT duplicates.
	// Uses canonical ordering (smaller ULID first) to prevent storing both (A,B) and (B,A).
	// ON CONFLICT DO NOTHING handles the case where the pair already exists.
	InsertNotDuplicate(ctx context.Context, arg InsertNotDuplicateParams) error
	// Check if a pair of events has been marked as not-duplicates.
	// Uses canonical ordering to match regardless of argument order.
	IsNotDuplicate(ctx context.Context, arg IsNotDuplicateParams) (bool, error)
	ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error)
	ListActiveDeveloperInvitations(ctx context.Context) ([]DeveloperInvitation, error)
	// Developer API key operations
	ListDeveloperAPIKeys(ctx context.Context, developerID pgtype.UUID) ([]ApiKey, error)
	ListDevelopers(ctx context.Context, arg ListDevelopersParams) ([]Developer, error)
	// SQLc queries for change feeds.
	ListEventChanges(ctx context.Context, arg ListEventChangesParams) ([]ListEventChangesRow, error)
	ListEventTombstones(ctx context.Context, arg ListEventTombstonesParams) ([]EventTombstone, error)
	ListFederationNodes(ctx context.Context, arg ListFederationNodesParams) ([]FederationNode, error)
	// List all events that have been confirmed as NOT duplicates of a given event.
	// Returns both sides of the pair (the given event could be event_id_a or event_id_b).
	ListNotDuplicatesForEvent(ctx context.Context, eventID string) ([]EventNotDuplicate, error)
	// SQLc queries for organizations domain.
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error)
	ListPendingInvitationsForUser(ctx context.Context, userID pgtype.UUID) ([]ListPendingInvitationsForUserRow, error)
	// SQLc queries for places domain.
	ListPlaces(ctx context.Context, arg ListPlacesParams) ([]ListPlacesRow, error)
	// List reviews with pagination and status filter
	ListReviewQueue(ctx context.Context, arg ListReviewQueueParams) ([]ListReviewQueueRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListUsersWithFilters(ctx context.Context, arg ListUsersWithFiltersParams) ([]ListUsersWithFiltersRow, error)
	MarkInvitationAccepted(ctx context.Context, id pgtype.UUID) error
	// Mark events as deleted before cleaning up their pending reviews
	MarkUnreviewedEventsAsDeleted(ctx context.Context) error
	MergeEventIntoDuplicate(ctx context.Context, arg MergeEventIntoDuplicateParams) error
	// Mark review as rejected
	RejectReview(ctx context.Context, arg RejectReviewParams) (EventReviewQueue, error)
	// Follow the merged_into_id chain from a given ULID to find the final canonical event.
	// Uses a recursive CTE with a max depth of 10 to prevent infinite loops.
	// Returns the ULID of the final canonical event (the one that is not itself merged).
	ResolveCanonicalEventULID(ctx context.Context, ulid string) (string, error)
	SoftDeleteEvent(ctx context.Context, arg SoftDeleteEventParams) error
	SoftDeleteOrganization(ctx context.Context, arg SoftDeleteOrganizationParams) error
	SoftDeletePlace(ctx context.Context, arg SoftDeletePlaceParams) error
	// Marks a field provenance record as superseded by a new record
	SupersedeFieldProvenance(ctx context.Context, arg SupersedeFieldProvenanceParams) error
	UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateDeveloper(ctx context.Context, arg UpdateDeveloperParams) (Developer, error)
	UpdateDeveloperLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error)
	UpdateFederationNode(ctx context.Context, arg UpdateFederationNodeParams) (FederationNode, error)
	UpdateFederationNodeHealth(ctx context.Context, arg UpdateFederationNodeHealthParams) error
	UpdateFederationNodeSyncStatus(ctx context.Context, arg UpdateFederationNodeSyncStatusParams) error
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
	// Flatten existing merge chains: update all events that point to an old target
	// to point to the new canonical target instead. This prevents transitive chains.
	// $1 = old target event ULID (intermediate node being re-pointed)
	// $2 = new canonical target event ULID (final destination)
	UpdateMergedIntoChain(ctx context.Context, arg UpdateMergedIntoChainParams) error
	// Update the start_time and end_time of all occurrences for an event identified by ULID.
	// Used by the FixReview workflow to correct occurrence dates during admin review.
	UpdateOccurrenceDatesByEventULID(ctx context.Context, arg UpdateOccurrenceDatesByEventULIDParams) error
	// Update existing review entry (for resubmissions with same issues)
	UpdateReviewQueueEntry(ctx context.Context, arg UpdateReviewQueueEntryParams) (EventReviewQueue, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// SQLc queries for API key usage tracking.
	UpsertAPIKeyUsage(ctx context.Context, arg UpsertAPIKeyUsageParams) error
	UpsertFederatedEvent(ctx context.Context, arg UpsertFederatedEventParams) (Event, error)
}

var _ Querier = (*Queries)(nil)
