// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptDeveloperInvitation(ctx context.Context, id pgtype.UUID) error
	ActivateUser(ctx context.Context, id pgtype.UUID) error
	// Mark review as approved
	ApproveReview(ctx context.Context, arg ApproveReviewParams) (EventReviewQueue, error)
	CheckAPIKeyOwnership(ctx context.Context, arg CheckAPIKeyOwnershipParams) (bool, error)
	// Archive old approved/superseded/merged reviews (90 day retention)
	CleanupArchivedReviews(ctx context.Context) error
	// Delete expired cache entries
	CleanupExpiredCache(ctx context.Context) (pgconn.CommandTag, error)
	// Delete rejected reviews for past events (7 day grace period)
	CleanupExpiredRejections(ctx context.Context) error
	// Delete pending reviews for events that have already started (too late to review)
	CleanupUnreviewedEvents(ctx context.Context) error
	CountAllEvents(ctx context.Context) (int64, error)
	CountAllOrganizations(ctx context.Context) (int64, error)
	CountAllPlaces(ctx context.Context) (int64, error)
	// SQLc queries for sources registry.
	CountAllSources(ctx context.Context) (int64, error)
	CountAllUsers(ctx context.Context) (int64, error)
	CountDeveloperAPIKeys(ctx context.Context, developerID pgtype.UUID) (int64, error)
	CountDevelopers(ctx context.Context) (int64, error)
	CountEventsByLifecycleState(ctx context.Context, lifecycleState string) (int64, error)
	CountEventsCreatedSince(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	CountPastEvents(ctx context.Context) (int64, error)
	// Count total reviews by status (for badge display)
	CountReviewQueueByStatus(ctx context.Context, status pgtype.Text) (int64, error)
	// Count entities of a type that have no external identifiers
	CountUnreconciledEntities(ctx context.Context) (int64, error)
	CountUpcomingEvents(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateBatchIngestionResult(ctx context.Context, arg CreateBatchIngestionResultParams) error
	// SQLc queries for developer management and invitations.
	// Developer CRUD operations
	CreateDeveloper(ctx context.Context, arg CreateDeveloperParams) (Developer, error)
	CreateDeveloperAPIKey(ctx context.Context, arg CreateDeveloperAPIKeyParams) (CreateDeveloperAPIKeyRow, error)
	// Developer invitation operations
	CreateDeveloperInvitation(ctx context.Context, arg CreateDeveloperInvitationParams) (DeveloperInvitation, error)
	CreateEventTombstone(ctx context.Context, arg CreateEventTombstoneParams) error
	CreateFederatedEventOccurrence(ctx context.Context, arg CreateFederatedEventOccurrenceParams) error
	// SQLc queries for federation sync.
	CreateFederationNode(ctx context.Context, arg CreateFederationNodeParams) (FederationNode, error)
	CreateOrganizationTombstone(ctx context.Context, arg CreateOrganizationTombstoneParams) error
	CreatePlaceTombstone(ctx context.Context, arg CreatePlaceTombstoneParams) error
	// Create new review queue entry
	CreateReviewQueueEntry(ctx context.Context, arg CreateReviewQueueEntryParams) (EventReviewQueue, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// User Invitation Queries
	CreateUserInvitation(ctx context.Context, arg CreateUserInvitationParams) (CreateUserInvitationRow, error)
	DeactivateAPIKey(ctx context.Context, id pgtype.UUID) error
	DeactivateDeveloper(ctx context.Context, id pgtype.UUID) error
	// User Management Queries
	DeactivateUser(ctx context.Context, id pgtype.UUID) error
	// Delete a specific entity identifier
	DeleteEntityIdentifier(ctx context.Context, id int32) error
	DeleteFederationNode(ctx context.Context, id pgtype.UUID) error
	// Delete a scraper source by name.
	DeleteScraperSource(ctx context.Context, name string) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	// Expires all pending (non-accepted, non-expired) invitations for a user by
	// setting accepted_at. This satisfies the unique partial index
	// idx_user_invitations_active (WHERE accepted_at IS NULL), allowing a new
	// invitation to be created. These rows are distinguishable from genuinely
	// accepted invitations because they will not have a corresponding password set.
	ExpirePendingInvitationsForUser(ctx context.Context, userID pgtype.UUID) error
	// SQLc queries for event_review_queue domain.
	// See docs/architecture/event-review-workflow.md for complete design.
	// Find existing review by deduplication keys (checks source_external_id or dedup_hash)
	FindReviewByDedup(ctx context.Context, arg FindReviewByDedupParams) (FindReviewByDedupRow, error)
	GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error)
	GetAPIKeyUsage(ctx context.Context, arg GetAPIKeyUsageParams) ([]ApiKeyUsage, error)
	GetAPIKeyUsageTotal(ctx context.Context, arg GetAPIKeyUsageTotalParams) (GetAPIKeyUsageTotalRow, error)
	// SQLc queries for knowledge graph reconciliation.
	// Get active knowledge graph authorities ordered by priority
	GetActiveAuthorities(ctx context.Context) ([]KnowledgeGraphAuthority, error)
	// Gets complete provenance history for a field, including superseded records
	GetAllFieldProvenanceHistory(ctx context.Context, arg GetAllFieldProvenanceHistoryParams) ([]GetAllFieldProvenanceHistoryRow, error)
	// Get active authorities applicable to a given event domain
	GetAuthoritiesForDomain(ctx context.Context, domain string) ([]KnowledgeGraphAuthority, error)
	GetAuthorityByCode(ctx context.Context, authorityCode string) (KnowledgeGraphAuthority, error)
	// SQLc queries for batch ingestion operations.
	GetBatchIngestionResult(ctx context.Context, batchID string) (BatchIngestionResult, error)
	// Gets the canonical (winning) field value based on conflict resolution rules
	// Priority: trust_level DESC, confidence DESC, observed_at DESC
	GetCanonicalFieldValue(ctx context.Context, arg GetCanonicalFieldValueParams) (GetCanonicalFieldValueRow, error)
	GetDeveloperByEmail(ctx context.Context, email string) (Developer, error)
	GetDeveloperByGitHubID(ctx context.Context, githubID pgtype.Int8) (Developer, error)
	GetDeveloperByID(ctx context.Context, id pgtype.UUID) (Developer, error)
	GetDeveloperInvitationByTokenHash(ctx context.Context, tokenHash string) (DeveloperInvitation, error)
	GetDeveloperUsageTotal(ctx context.Context, arg GetDeveloperUsageTotalParams) (GetDeveloperUsageTotalRow, error)
	// Get all external identifiers for an entity
	GetEntityIdentifiers(ctx context.Context, arg GetEntityIdentifiersParams) ([]EntityIdentifier, error)
	// Get identifiers for an entity from a specific authority
	GetEntityIdentifiersByAuthority(ctx context.Context, arg GetEntityIdentifiersByAuthorityParams) ([]EntityIdentifier, error)
	// Federation Sync Queries
	GetEventByFederationURI(ctx context.Context, federationUri pgtype.Text) (Event, error)
	// SQLc queries for events domain.
	GetEventByULID(ctx context.Context, ulid string) ([]GetEventByULIDRow, error)
	GetEventChangeByID(ctx context.Context, id pgtype.UUID) (GetEventChangeByIDRow, error)
	GetEventDateRange(ctx context.Context) (GetEventDateRangeRow, error)
	// SQLc queries for provenance tracking.
	// Retrieves all sources for a given event with source metadata and timestamps (FR-029)
	GetEventSources(ctx context.Context, eventID pgtype.UUID) ([]GetEventSourcesRow, error)
	GetEventTombstoneByEventID(ctx context.Context, eventID pgtype.UUID) (EventTombstone, error)
	GetEventTombstoneByEventULID(ctx context.Context, ulid string) (EventTombstone, error)
	GetEventTombstoneByURI(ctx context.Context, eventUri string) (EventTombstone, error)
	GetFederationNodeByDomain(ctx context.Context, nodeDomain string) (FederationNode, error)
	GetFederationNodeByID(ctx context.Context, id pgtype.UUID) (FederationNode, error)
	// Retrieves field-level provenance for an event, optionally filtered by field paths
	// Includes source metadata and timestamps per FR-024 and FR-029
	GetFieldProvenance(ctx context.Context, eventID pgtype.UUID) ([]GetFieldProvenanceRow, error)
	// Retrieves field-level provenance for specific field paths on an event
	GetFieldProvenanceForPaths(ctx context.Context, arg GetFieldProvenanceForPathsParams) ([]GetFieldProvenanceForPathsRow, error)
	GetIdempotencyKey(ctx context.Context, key string) (GetIdempotencyKeyRow, error)
	GetLatestEventChange(ctx context.Context) (GetLatestEventChangeRow, error)
	// Get the most recent scraper run for a given source_name.
	GetLatestScraperRunBySource(ctx context.Context, sourceName string) (ScraperRun, error)
	GetOrganizationByULID(ctx context.Context, ulid string) (GetOrganizationByULIDRow, error)
	GetOrganizationTombstoneByULID(ctx context.Context, ulid string) (OrganizationTombstone, error)
	GetPlaceByULID(ctx context.Context, ulid string) (GetPlaceByULIDRow, error)
	GetPlaceTombstoneByULID(ctx context.Context, ulid string) (PlaceTombstone, error)
	// Check cache for a previous reconciliation result
	GetReconciliationCache(ctx context.Context, arg GetReconciliationCacheParams) (ReconciliationCache, error)
	// Get single review by ID
	GetReviewQueueEntry(ctx context.Context, id int32) (GetReviewQueueEntryRow, error)
	// Get a single scraper source by primary key.
	GetScraperSourceByID(ctx context.Context, id int64) (ScraperSource, error)
	// Get a single scraper source by unique name.
	GetScraperSourceByName(ctx context.Context, name string) (ScraperSource, error)
	// Retrieves source metadata by ID
	GetSourceByID(ctx context.Context, id pgtype.UUID) (GetSourceByIDRow, error)
	// Gets all sources that contributed to an event (deduplicated)
	GetSourcesByEventID(ctx context.Context, eventID pgtype.UUID) ([]GetSourcesByEventIDRow, error)
	// SQLc queries for authentication.
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserInvitationByTokenHash(ctx context.Context, tokenHash string) (UserInvitation, error)
	// Records a source's contribution to an event with source and received timestamps (FR-029)
	InsertEventSource(ctx context.Context, arg InsertEventSourceParams) (EventSource, error)
	// Records field-level provenance with source timestamp
	InsertFieldProvenance(ctx context.Context, arg InsertFieldProvenanceParams) (FieldProvenance, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (InsertIdempotencyKeyRow, error)
	// SQLc queries for event_not_duplicates table.
	// Tracks pairs of events that an admin has confirmed are NOT duplicates,
	// preventing them from being re-flagged during near-duplicate detection.
	// Record that two events are confirmed as NOT duplicates.
	// Uses canonical ordering (smaller ULID first) to prevent storing both (A,B) and (B,A).
	// ON CONFLICT DO NOTHING handles the case where the pair already exists.
	InsertNotDuplicate(ctx context.Context, arg InsertNotDuplicateParams) error
	// SQLc queries for scraper runs tracking.
	// Insert a new scraper run record and return its id.
	InsertScraperRun(ctx context.Context, arg InsertScraperRunParams) (int64, error)
	// Check if a pair of events has been marked as not-duplicates.
	// Uses canonical ordering to match regardless of argument order.
	IsNotDuplicate(ctx context.Context, arg IsNotDuplicateParams) (bool, error)
	// Associate an organization with a scraper source.
	LinkOrgScraperSource(ctx context.Context, arg LinkOrgScraperSourceParams) error
	// Associate a place with a scraper source.
	LinkPlaceScraperSource(ctx context.Context, arg LinkPlaceScraperSourceParams) error
	ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error)
	ListActiveDeveloperInvitations(ctx context.Context) ([]DeveloperInvitation, error)
	// Developer API key operations
	ListDeveloperAPIKeys(ctx context.Context, developerID pgtype.UUID) ([]ApiKey, error)
	ListDevelopers(ctx context.Context, arg ListDevelopersParams) ([]Developer, error)
	// SQLc queries for change feeds.
	ListEventChanges(ctx context.Context, arg ListEventChangesParams) ([]ListEventChangesRow, error)
	ListEventTombstones(ctx context.Context, arg ListEventTombstonesParams) ([]EventTombstone, error)
	ListFederationNodes(ctx context.Context, arg ListFederationNodesParams) ([]FederationNode, error)
	// List all events that have been confirmed as NOT duplicates of a given event.
	// Returns both sides of the pair (the given event could be event_id_a or event_id_b).
	ListNotDuplicatesForEvent(ctx context.Context, eventID string) ([]EventNotDuplicate, error)
	// SQLc queries for organizations domain.
	ListOrganizationsByCreatedAt(ctx context.Context, arg ListOrganizationsByCreatedAtParams) ([]ListOrganizationsByCreatedAtRow, error)
	ListOrganizationsByCreatedAtDesc(ctx context.Context, arg ListOrganizationsByCreatedAtDescParams) ([]ListOrganizationsByCreatedAtDescRow, error)
	ListOrganizationsByName(ctx context.Context, arg ListOrganizationsByNameParams) ([]ListOrganizationsByNameRow, error)
	ListOrganizationsByNameDesc(ctx context.Context, arg ListOrganizationsByNameDescParams) ([]ListOrganizationsByNameDescRow, error)
	ListPendingInvitationsForUser(ctx context.Context, userID pgtype.UUID) ([]ListPendingInvitationsForUserRow, error)
	// SQLc queries for places domain.
	ListPlacesByCreatedAt(ctx context.Context, arg ListPlacesByCreatedAtParams) ([]ListPlacesByCreatedAtRow, error)
	ListPlacesByCreatedAtDesc(ctx context.Context, arg ListPlacesByCreatedAtDescParams) ([]ListPlacesByCreatedAtDescRow, error)
	ListPlacesByName(ctx context.Context, arg ListPlacesByNameParams) ([]ListPlacesByNameRow, error)
	ListPlacesByNameDesc(ctx context.Context, arg ListPlacesByNameDescParams) ([]ListPlacesByNameDescRow, error)
	// List the N most recent scraper runs ordered by started_at DESC.
	ListRecentScraperRuns(ctx context.Context, limit int32) ([]ScraperRun, error)
	// List reviews with pagination and status filter
	ListReviewQueue(ctx context.Context, arg ListReviewQueueParams) ([]ListReviewQueueRow, error)
	// List all scraper sources, optionally filtered by enabled flag.
	ListScraperSources(ctx context.Context, enabled pgtype.Bool) ([]ScraperSource, error)
	// List all scraper sources linked to a given organization.
	ListScraperSourcesByOrg(ctx context.Context, organizationID pgtype.UUID) ([]ScraperSource, error)
	// List all scraper sources linked to a given place.
	ListScraperSourcesByPlace(ctx context.Context, placeID pgtype.UUID) ([]ScraperSource, error)
	// Get organizations that have no external identifiers, ordered by creation date
	ListUnreconciledOrganizations(ctx context.Context, maxResults int32) ([]ListUnreconciledOrganizationsRow, error)
	// Get places that have no external identifiers, ordered by creation date
	ListUnreconciledPlaces(ctx context.Context, maxResults int32) ([]ListUnreconciledPlacesRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListUsersWithFilters(ctx context.Context, arg ListUsersWithFiltersParams) ([]ListUsersWithFiltersRow, error)
	MarkInvitationAccepted(ctx context.Context, id pgtype.UUID) error
	// Mark events as deleted before cleaning up their pending reviews
	MarkUnreviewedEventsAsDeleted(ctx context.Context) error
	MergeEventIntoDuplicate(ctx context.Context, arg MergeEventIntoDuplicateParams) error
	// Mark review as rejected
	RejectReview(ctx context.Context, arg RejectReviewParams) (EventReviewQueue, error)
	// Follow the merged_into_id chain from a given ULID to find the final canonical event.
	// Uses a recursive CTE with a max depth of 10 to prevent infinite loops.
	// Returns the ULID of the final canonical event (the one that is not itself merged).
	ResolveCanonicalEventULID(ctx context.Context, ulid string) (string, error)
	RevokeAllDeveloperAPIKeys(ctx context.Context, developerID pgtype.UUID) (int64, error)
	SoftDeleteEvent(ctx context.Context, arg SoftDeleteEventParams) error
	SoftDeleteOrganization(ctx context.Context, arg SoftDeleteOrganizationParams) error
	SoftDeletePlace(ctx context.Context, arg SoftDeletePlaceParams) error
	// Marks a field provenance record as superseded by a new record
	SupersedeFieldProvenance(ctx context.Context, arg SupersedeFieldProvenanceParams) error
	// Remove an organization↔scraper source association.
	UnlinkOrgScraperSource(ctx context.Context, arg UnlinkOrgScraperSourceParams) error
	// Remove a place↔scraper source association.
	UnlinkPlaceScraperSource(ctx context.Context, arg UnlinkPlaceScraperSourceParams) error
	UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateDeveloper(ctx context.Context, arg UpdateDeveloperParams) (Developer, error)
	UpdateDeveloperLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error)
	UpdateFederationNode(ctx context.Context, arg UpdateFederationNodeParams) (FederationNode, error)
	UpdateFederationNodeHealth(ctx context.Context, arg UpdateFederationNodeHealthParams) error
	UpdateFederationNodeSyncStatus(ctx context.Context, arg UpdateFederationNodeSyncStatusParams) error
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
	// Flatten existing merge chains: update all events that point to an old target
	// to point to the new canonical target instead. This prevents transitive chains.
	// $1 = old target event ULID (intermediate node being re-pointed)
	// $2 = new canonical target event ULID (final destination)
	UpdateMergedIntoChain(ctx context.Context, arg UpdateMergedIntoChainParams) error
	// Update the start_time and end_time of all occurrences for an event identified by ULID.
	// Used by the FixReview workflow to correct occurrence dates during admin review.
	UpdateOccurrenceDatesByEventULID(ctx context.Context, arg UpdateOccurrenceDatesByEventULIDParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (UpdateOrganizationRow, error)
	UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (UpdatePlaceRow, error)
	// Update existing review entry (for resubmissions with same issues)
	UpdateReviewQueueEntry(ctx context.Context, arg UpdateReviewQueueEntryParams) (EventReviewQueue, error)
	// Mark a scraper run as completed with event counts.
	UpdateScraperRunCompleted(ctx context.Context, arg UpdateScraperRunCompletedParams) error
	// Mark a scraper run as failed with an error message.
	UpdateScraperRunFailed(ctx context.Context, arg UpdateScraperRunFailedParams) error
	// Update last_scraped_at timestamp after a successful scrape run.
	UpdateScraperSourceLastScraped(ctx context.Context, name string) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// SQLc queries for API key usage tracking.
	UpsertAPIKeyUsage(ctx context.Context, arg UpsertAPIKeyUsageParams) error
	// Insert or update an entity identifier (sameAs link)
	UpsertEntityIdentifier(ctx context.Context, arg UpsertEntityIdentifierParams) (EntityIdentifier, error)
	UpsertFederatedEvent(ctx context.Context, arg UpsertFederatedEventParams) (Event, error)
	// Insert or update a cache entry
	UpsertReconciliationCache(ctx context.Context, arg UpsertReconciliationCacheParams) (ReconciliationCache, error)
	// SQLc queries for scraper_sources and linkage tables.
	// Insert or update a scraper source by name (used by 'server scrape sync').
	UpsertScraperSource(ctx context.Context, arg UpsertScraperSourceParams) (ScraperSource, error)
}

var _ Querier = (*Queries)(nil)
