// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scraper_submissions.sql

package postgres

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingValidation = `-- name: CountPendingValidation :one
SELECT COUNT(*)
  FROM scraper_submissions
 WHERE status = 'pending_validation'
`

// Count rows currently awaiting async URL validation.
func (q *Queries) CountPendingValidation(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingValidation)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentSubmissionsByIP = `-- name: CountRecentSubmissionsByIP :one
SELECT COUNT(*)
  FROM scraper_submissions
 WHERE submitter_ip = $1::INET
   AND submitted_at > NOW() - $2::INTERVAL
`

type CountRecentSubmissionsByIPParams struct {
	SubmitterIp netip.Addr      `json:"submitter_ip"`
	Interval    pgtype.Interval `json:"interval"`
}

// Count submissions from a given IP within the provided interval (for rate limiting).
func (q *Queries) CountRecentSubmissionsByIP(ctx context.Context, arg CountRecentSubmissionsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentSubmissionsByIP, arg.SubmitterIp, arg.Interval)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScraperSubmissions = `-- name: CountScraperSubmissions :one
SELECT COUNT(*)
  FROM scraper_submissions
 WHERE ($1::TEXT IS NULL OR status = $1)
`

// Count submissions with optional status filter (for pagination total).
func (q *Queries) CountScraperSubmissions(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countScraperSubmissions, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRecentSubmissionByURLNorm = `-- name: GetRecentSubmissionByURLNorm :one
SELECT id, url, url_norm, submitted_at, submitter_ip, status,
       rejection_reason, notes, validated_at
  FROM scraper_submissions
 WHERE url_norm     = $1
   AND submitted_at > NOW() - $2::INTERVAL
 ORDER BY submitted_at DESC
 LIMIT 1
`

type GetRecentSubmissionByURLNormParams struct {
	UrlNorm  string          `json:"url_norm"`
	Interval pgtype.Interval `json:"interval"`
}

// Check if a url_norm was submitted within the given interval (for dedup).
// Returns the most recent matching row if found.
func (q *Queries) GetRecentSubmissionByURLNorm(ctx context.Context, arg GetRecentSubmissionByURLNormParams) (ScraperSubmission, error) {
	row := q.db.QueryRow(ctx, getRecentSubmissionByURLNorm, arg.UrlNorm, arg.Interval)
	var i ScraperSubmission
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.UrlNorm,
		&i.SubmittedAt,
		&i.SubmitterIp,
		&i.Status,
		&i.RejectionReason,
		&i.Notes,
		&i.ValidatedAt,
	)
	return i, err
}

const insertScraperSubmission = `-- name: InsertScraperSubmission :one

INSERT INTO scraper_submissions (
  url,
  url_norm,
  submitter_ip,
  status
) VALUES (
  $1,
  $2,
  $3,
  'pending_validation'
)
RETURNING id, url, url_norm, submitted_at, submitter_ip, status,
          rejection_reason, notes, validated_at
`

type InsertScraperSubmissionParams struct {
	Url         string     `json:"url"`
	UrlNorm     string     `json:"url_norm"`
	SubmitterIp netip.Addr `json:"submitter_ip"`
}

// SQLc queries for scraper_submissions.
// Insert a new URL submission and return the full row.
func (q *Queries) InsertScraperSubmission(ctx context.Context, arg InsertScraperSubmissionParams) (ScraperSubmission, error) {
	row := q.db.QueryRow(ctx, insertScraperSubmission, arg.Url, arg.UrlNorm, arg.SubmitterIp)
	var i ScraperSubmission
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.UrlNorm,
		&i.SubmittedAt,
		&i.SubmitterIp,
		&i.Status,
		&i.RejectionReason,
		&i.Notes,
		&i.ValidatedAt,
	)
	return i, err
}

const listPendingValidation = `-- name: ListPendingValidation :many
SELECT id, url, url_norm, submitted_at, submitter_ip, status,
       rejection_reason, notes, validated_at
  FROM scraper_submissions
 WHERE status = 'pending_validation'
 ORDER BY submitted_at ASC
 LIMIT $1::INT
`

// Fetch up to N rows awaiting async URL validation, oldest first.
func (q *Queries) ListPendingValidation(ctx context.Context, limit int32) ([]ScraperSubmission, error) {
	rows, err := q.db.Query(ctx, listPendingValidation, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScraperSubmission{}
	for rows.Next() {
		var i ScraperSubmission
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.UrlNorm,
			&i.SubmittedAt,
			&i.SubmitterIp,
			&i.Status,
			&i.RejectionReason,
			&i.Notes,
			&i.ValidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScraperSubmissions = `-- name: ListScraperSubmissions :many
SELECT id, url, url_norm, submitted_at, submitter_ip, status,
       rejection_reason, notes, validated_at
  FROM scraper_submissions
 WHERE ($1::TEXT IS NULL OR status = $1)
 ORDER BY submitted_at DESC
 LIMIT  $3::INT
 OFFSET $2::INT
`

type ListScraperSubmissionsParams struct {
	Status pgtype.Text `json:"status"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

// Paginated list of submissions, optionally filtered by status (for admin).
func (q *Queries) ListScraperSubmissions(ctx context.Context, arg ListScraperSubmissionsParams) ([]ScraperSubmission, error) {
	rows, err := q.db.Query(ctx, listScraperSubmissions, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScraperSubmission{}
	for rows.Next() {
		var i ScraperSubmission
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.UrlNorm,
			&i.SubmittedAt,
			&i.SubmitterIp,
			&i.Status,
			&i.RejectionReason,
			&i.Notes,
			&i.ValidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubmissionAdminReview = `-- name: UpdateSubmissionAdminReview :one
UPDATE scraper_submissions
   SET status = $1,
       notes  = $2
 WHERE id = $3
RETURNING id, url, url_norm, submitted_at, submitter_ip, status,
          rejection_reason, notes, validated_at
`

type UpdateSubmissionAdminReviewParams struct {
	Status string      `json:"status"`
	Notes  pgtype.Text `json:"notes"`
	ID     int64       `json:"id"`
}

// Update status and optional notes for a given row (admin PATCH).
// Returns the full updated row.
func (q *Queries) UpdateSubmissionAdminReview(ctx context.Context, arg UpdateSubmissionAdminReviewParams) (ScraperSubmission, error) {
	row := q.db.QueryRow(ctx, updateSubmissionAdminReview, arg.Status, arg.Notes, arg.ID)
	var i ScraperSubmission
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.UrlNorm,
		&i.SubmittedAt,
		&i.SubmitterIp,
		&i.Status,
		&i.RejectionReason,
		&i.Notes,
		&i.ValidatedAt,
	)
	return i, err
}

const updateSubmissionStatus = `-- name: UpdateSubmissionStatus :exec
UPDATE scraper_submissions
   SET status           = $1,
       rejection_reason = $2,
       validated_at     = $3
 WHERE id = $4
`

type UpdateSubmissionStatusParams struct {
	Status          string             `json:"status"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	ValidatedAt     pgtype.Timestamptz `json:"validated_at"`
	ID              int64              `json:"id"`
}

// Update status, optional rejection_reason, and optional validated_at for a given row.
// Used by the background validation worker.
func (q *Queries) UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionStatus,
		arg.Status,
		arg.RejectionReason,
		arg.ValidatedAt,
		arg.ID,
	)
	return err
}
