// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scraper_sources.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteScraperSource = `-- name: DeleteScraperSource :exec
DELETE FROM scraper_sources WHERE name = $1
`

// Delete a scraper source by name.
func (q *Queries) DeleteScraperSource(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteScraperSource, name)
	return err
}

const getScraperSourceByID = `-- name: GetScraperSourceByID :one
SELECT id, name, url, urls, tier, schedule, trust_level, license, enabled,
       max_pages, selectors, notes, event_url_pattern, skip_multi_session_check,
       multi_session_duration_threshold, follow_event_urls, timezone,
       last_scraped_at, created_at, updated_at,
       headless_wait_selector, headless_wait_timeout_ms, headless_pagination_btn,
       headless_headers, headless_rate_limit_ms,
       headless_wait_network_idle, headless_undetected, headless_iframe, headless_intercept,
       graphql_config, rest_config, sitemap_config
  FROM scraper_sources
 WHERE id = $1
`

type GetScraperSourceByIDRow struct {
	ID                            int64              `json:"id"`
	Name                          string             `json:"name"`
	Url                           string             `json:"url"`
	Urls                          []string           `json:"urls"`
	Tier                          int32              `json:"tier"`
	Schedule                      string             `json:"schedule"`
	TrustLevel                    int32              `json:"trust_level"`
	License                       string             `json:"license"`
	Enabled                       bool               `json:"enabled"`
	MaxPages                      int32              `json:"max_pages"`
	Selectors                     []byte             `json:"selectors"`
	Notes                         pgtype.Text        `json:"notes"`
	EventUrlPattern               string             `json:"event_url_pattern"`
	SkipMultiSessionCheck         bool               `json:"skip_multi_session_check"`
	MultiSessionDurationThreshold string             `json:"multi_session_duration_threshold"`
	FollowEventUrls               bool               `json:"follow_event_urls"`
	Timezone                      string             `json:"timezone"`
	LastScrapedAt                 pgtype.Timestamptz `json:"last_scraped_at"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	HeadlessWaitSelector          pgtype.Text        `json:"headless_wait_selector"`
	HeadlessWaitTimeoutMs         int32              `json:"headless_wait_timeout_ms"`
	HeadlessPaginationBtn         pgtype.Text        `json:"headless_pagination_btn"`
	HeadlessHeaders               []byte             `json:"headless_headers"`
	HeadlessRateLimitMs           int32              `json:"headless_rate_limit_ms"`
	HeadlessWaitNetworkIdle       bool               `json:"headless_wait_network_idle"`
	HeadlessUndetected            bool               `json:"headless_undetected"`
	HeadlessIframe                []byte             `json:"headless_iframe"`
	HeadlessIntercept             []byte             `json:"headless_intercept"`
	GraphqlConfig                 []byte             `json:"graphql_config"`
	RestConfig                    []byte             `json:"rest_config"`
	SitemapConfig                 []byte             `json:"sitemap_config"`
}

// Get a single scraper source by primary key.
func (q *Queries) GetScraperSourceByID(ctx context.Context, id int64) (GetScraperSourceByIDRow, error) {
	row := q.db.QueryRow(ctx, getScraperSourceByID, id)
	var i GetScraperSourceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Urls,
		&i.Tier,
		&i.Schedule,
		&i.TrustLevel,
		&i.License,
		&i.Enabled,
		&i.MaxPages,
		&i.Selectors,
		&i.Notes,
		&i.EventUrlPattern,
		&i.SkipMultiSessionCheck,
		&i.MultiSessionDurationThreshold,
		&i.FollowEventUrls,
		&i.Timezone,
		&i.LastScrapedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlessWaitSelector,
		&i.HeadlessWaitTimeoutMs,
		&i.HeadlessPaginationBtn,
		&i.HeadlessHeaders,
		&i.HeadlessRateLimitMs,
		&i.HeadlessWaitNetworkIdle,
		&i.HeadlessUndetected,
		&i.HeadlessIframe,
		&i.HeadlessIntercept,
		&i.GraphqlConfig,
		&i.RestConfig,
		&i.SitemapConfig,
	)
	return i, err
}

const getScraperSourceByName = `-- name: GetScraperSourceByName :one
SELECT id, name, url, urls, tier, schedule, trust_level, license, enabled,
       max_pages, selectors, notes, event_url_pattern, skip_multi_session_check,
       multi_session_duration_threshold, follow_event_urls, timezone,
       last_scraped_at, created_at, updated_at,
       headless_wait_selector, headless_wait_timeout_ms, headless_pagination_btn,
       headless_headers, headless_rate_limit_ms,
       headless_wait_network_idle, headless_undetected, headless_iframe, headless_intercept,
       graphql_config, rest_config, sitemap_config
  FROM scraper_sources
 WHERE name = $1
`

type GetScraperSourceByNameRow struct {
	ID                            int64              `json:"id"`
	Name                          string             `json:"name"`
	Url                           string             `json:"url"`
	Urls                          []string           `json:"urls"`
	Tier                          int32              `json:"tier"`
	Schedule                      string             `json:"schedule"`
	TrustLevel                    int32              `json:"trust_level"`
	License                       string             `json:"license"`
	Enabled                       bool               `json:"enabled"`
	MaxPages                      int32              `json:"max_pages"`
	Selectors                     []byte             `json:"selectors"`
	Notes                         pgtype.Text        `json:"notes"`
	EventUrlPattern               string             `json:"event_url_pattern"`
	SkipMultiSessionCheck         bool               `json:"skip_multi_session_check"`
	MultiSessionDurationThreshold string             `json:"multi_session_duration_threshold"`
	FollowEventUrls               bool               `json:"follow_event_urls"`
	Timezone                      string             `json:"timezone"`
	LastScrapedAt                 pgtype.Timestamptz `json:"last_scraped_at"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	HeadlessWaitSelector          pgtype.Text        `json:"headless_wait_selector"`
	HeadlessWaitTimeoutMs         int32              `json:"headless_wait_timeout_ms"`
	HeadlessPaginationBtn         pgtype.Text        `json:"headless_pagination_btn"`
	HeadlessHeaders               []byte             `json:"headless_headers"`
	HeadlessRateLimitMs           int32              `json:"headless_rate_limit_ms"`
	HeadlessWaitNetworkIdle       bool               `json:"headless_wait_network_idle"`
	HeadlessUndetected            bool               `json:"headless_undetected"`
	HeadlessIframe                []byte             `json:"headless_iframe"`
	HeadlessIntercept             []byte             `json:"headless_intercept"`
	GraphqlConfig                 []byte             `json:"graphql_config"`
	RestConfig                    []byte             `json:"rest_config"`
	SitemapConfig                 []byte             `json:"sitemap_config"`
}

// Get a single scraper source by unique name.
func (q *Queries) GetScraperSourceByName(ctx context.Context, name string) (GetScraperSourceByNameRow, error) {
	row := q.db.QueryRow(ctx, getScraperSourceByName, name)
	var i GetScraperSourceByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Urls,
		&i.Tier,
		&i.Schedule,
		&i.TrustLevel,
		&i.License,
		&i.Enabled,
		&i.MaxPages,
		&i.Selectors,
		&i.Notes,
		&i.EventUrlPattern,
		&i.SkipMultiSessionCheck,
		&i.MultiSessionDurationThreshold,
		&i.FollowEventUrls,
		&i.Timezone,
		&i.LastScrapedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlessWaitSelector,
		&i.HeadlessWaitTimeoutMs,
		&i.HeadlessPaginationBtn,
		&i.HeadlessHeaders,
		&i.HeadlessRateLimitMs,
		&i.HeadlessWaitNetworkIdle,
		&i.HeadlessUndetected,
		&i.HeadlessIframe,
		&i.HeadlessIntercept,
		&i.GraphqlConfig,
		&i.RestConfig,
		&i.SitemapConfig,
	)
	return i, err
}

const linkOrgScraperSource = `-- name: LinkOrgScraperSource :exec
INSERT INTO org_scraper_sources (organization_id, scraper_source_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkOrgScraperSourceParams struct {
	OrganizationID  pgtype.UUID `json:"organization_id"`
	ScraperSourceID int64       `json:"scraper_source_id"`
}

// Associate an organization with a scraper source.
func (q *Queries) LinkOrgScraperSource(ctx context.Context, arg LinkOrgScraperSourceParams) error {
	_, err := q.db.Exec(ctx, linkOrgScraperSource, arg.OrganizationID, arg.ScraperSourceID)
	return err
}

const linkPlaceScraperSource = `-- name: LinkPlaceScraperSource :exec
INSERT INTO place_scraper_sources (place_id, scraper_source_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkPlaceScraperSourceParams struct {
	PlaceID         pgtype.UUID `json:"place_id"`
	ScraperSourceID int64       `json:"scraper_source_id"`
}

// Associate a place with a scraper source.
func (q *Queries) LinkPlaceScraperSource(ctx context.Context, arg LinkPlaceScraperSourceParams) error {
	_, err := q.db.Exec(ctx, linkPlaceScraperSource, arg.PlaceID, arg.ScraperSourceID)
	return err
}

const listScraperSources = `-- name: ListScraperSources :many
SELECT id, name, url, urls, tier, schedule, trust_level, license, enabled,
       max_pages, selectors, notes, event_url_pattern, skip_multi_session_check,
       multi_session_duration_threshold, follow_event_urls, timezone,
       last_scraped_at, created_at, updated_at,
       headless_wait_selector, headless_wait_timeout_ms, headless_pagination_btn,
       headless_headers, headless_rate_limit_ms,
       headless_wait_network_idle, headless_undetected, headless_iframe, headless_intercept,
       graphql_config, rest_config, sitemap_config
  FROM scraper_sources
 WHERE ($1::boolean IS NULL OR enabled = $1)
 ORDER BY name ASC
`

type ListScraperSourcesRow struct {
	ID                            int64              `json:"id"`
	Name                          string             `json:"name"`
	Url                           string             `json:"url"`
	Urls                          []string           `json:"urls"`
	Tier                          int32              `json:"tier"`
	Schedule                      string             `json:"schedule"`
	TrustLevel                    int32              `json:"trust_level"`
	License                       string             `json:"license"`
	Enabled                       bool               `json:"enabled"`
	MaxPages                      int32              `json:"max_pages"`
	Selectors                     []byte             `json:"selectors"`
	Notes                         pgtype.Text        `json:"notes"`
	EventUrlPattern               string             `json:"event_url_pattern"`
	SkipMultiSessionCheck         bool               `json:"skip_multi_session_check"`
	MultiSessionDurationThreshold string             `json:"multi_session_duration_threshold"`
	FollowEventUrls               bool               `json:"follow_event_urls"`
	Timezone                      string             `json:"timezone"`
	LastScrapedAt                 pgtype.Timestamptz `json:"last_scraped_at"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	HeadlessWaitSelector          pgtype.Text        `json:"headless_wait_selector"`
	HeadlessWaitTimeoutMs         int32              `json:"headless_wait_timeout_ms"`
	HeadlessPaginationBtn         pgtype.Text        `json:"headless_pagination_btn"`
	HeadlessHeaders               []byte             `json:"headless_headers"`
	HeadlessRateLimitMs           int32              `json:"headless_rate_limit_ms"`
	HeadlessWaitNetworkIdle       bool               `json:"headless_wait_network_idle"`
	HeadlessUndetected            bool               `json:"headless_undetected"`
	HeadlessIframe                []byte             `json:"headless_iframe"`
	HeadlessIntercept             []byte             `json:"headless_intercept"`
	GraphqlConfig                 []byte             `json:"graphql_config"`
	RestConfig                    []byte             `json:"rest_config"`
	SitemapConfig                 []byte             `json:"sitemap_config"`
}

// List all scraper sources, optionally filtered by enabled flag.
func (q *Queries) ListScraperSources(ctx context.Context, enabled pgtype.Bool) ([]ListScraperSourcesRow, error) {
	rows, err := q.db.Query(ctx, listScraperSources, enabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScraperSourcesRow{}
	for rows.Next() {
		var i ListScraperSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Urls,
			&i.Tier,
			&i.Schedule,
			&i.TrustLevel,
			&i.License,
			&i.Enabled,
			&i.MaxPages,
			&i.Selectors,
			&i.Notes,
			&i.EventUrlPattern,
			&i.SkipMultiSessionCheck,
			&i.MultiSessionDurationThreshold,
			&i.FollowEventUrls,
			&i.Timezone,
			&i.LastScrapedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HeadlessWaitSelector,
			&i.HeadlessWaitTimeoutMs,
			&i.HeadlessPaginationBtn,
			&i.HeadlessHeaders,
			&i.HeadlessRateLimitMs,
			&i.HeadlessWaitNetworkIdle,
			&i.HeadlessUndetected,
			&i.HeadlessIframe,
			&i.HeadlessIntercept,
			&i.GraphqlConfig,
			&i.RestConfig,
			&i.SitemapConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScraperSourcesByOrg = `-- name: ListScraperSourcesByOrg :many
SELECT s.id, s.name, s.url, s.urls, s.tier, s.schedule, s.trust_level, s.license, s.enabled,
       s.max_pages, s.selectors, s.notes, s.event_url_pattern, s.skip_multi_session_check,
       s.multi_session_duration_threshold, s.follow_event_urls, s.timezone,
       s.last_scraped_at, s.created_at, s.updated_at,
       s.headless_wait_selector, s.headless_wait_timeout_ms, s.headless_pagination_btn,
       s.headless_headers, s.headless_rate_limit_ms,
       s.headless_wait_network_idle, s.headless_undetected, s.headless_iframe, s.headless_intercept,
       s.graphql_config, s.rest_config, s.sitemap_config
  FROM scraper_sources s
  JOIN org_scraper_sources l ON l.scraper_source_id = s.id
 WHERE l.organization_id = $1
 ORDER BY s.name ASC
`

type ListScraperSourcesByOrgRow struct {
	ID                            int64              `json:"id"`
	Name                          string             `json:"name"`
	Url                           string             `json:"url"`
	Urls                          []string           `json:"urls"`
	Tier                          int32              `json:"tier"`
	Schedule                      string             `json:"schedule"`
	TrustLevel                    int32              `json:"trust_level"`
	License                       string             `json:"license"`
	Enabled                       bool               `json:"enabled"`
	MaxPages                      int32              `json:"max_pages"`
	Selectors                     []byte             `json:"selectors"`
	Notes                         pgtype.Text        `json:"notes"`
	EventUrlPattern               string             `json:"event_url_pattern"`
	SkipMultiSessionCheck         bool               `json:"skip_multi_session_check"`
	MultiSessionDurationThreshold string             `json:"multi_session_duration_threshold"`
	FollowEventUrls               bool               `json:"follow_event_urls"`
	Timezone                      string             `json:"timezone"`
	LastScrapedAt                 pgtype.Timestamptz `json:"last_scraped_at"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	HeadlessWaitSelector          pgtype.Text        `json:"headless_wait_selector"`
	HeadlessWaitTimeoutMs         int32              `json:"headless_wait_timeout_ms"`
	HeadlessPaginationBtn         pgtype.Text        `json:"headless_pagination_btn"`
	HeadlessHeaders               []byte             `json:"headless_headers"`
	HeadlessRateLimitMs           int32              `json:"headless_rate_limit_ms"`
	HeadlessWaitNetworkIdle       bool               `json:"headless_wait_network_idle"`
	HeadlessUndetected            bool               `json:"headless_undetected"`
	HeadlessIframe                []byte             `json:"headless_iframe"`
	HeadlessIntercept             []byte             `json:"headless_intercept"`
	GraphqlConfig                 []byte             `json:"graphql_config"`
	RestConfig                    []byte             `json:"rest_config"`
	SitemapConfig                 []byte             `json:"sitemap_config"`
}

// List all scraper sources linked to a given organization.
func (q *Queries) ListScraperSourcesByOrg(ctx context.Context, organizationID pgtype.UUID) ([]ListScraperSourcesByOrgRow, error) {
	rows, err := q.db.Query(ctx, listScraperSourcesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScraperSourcesByOrgRow{}
	for rows.Next() {
		var i ListScraperSourcesByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Urls,
			&i.Tier,
			&i.Schedule,
			&i.TrustLevel,
			&i.License,
			&i.Enabled,
			&i.MaxPages,
			&i.Selectors,
			&i.Notes,
			&i.EventUrlPattern,
			&i.SkipMultiSessionCheck,
			&i.MultiSessionDurationThreshold,
			&i.FollowEventUrls,
			&i.Timezone,
			&i.LastScrapedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HeadlessWaitSelector,
			&i.HeadlessWaitTimeoutMs,
			&i.HeadlessPaginationBtn,
			&i.HeadlessHeaders,
			&i.HeadlessRateLimitMs,
			&i.HeadlessWaitNetworkIdle,
			&i.HeadlessUndetected,
			&i.HeadlessIframe,
			&i.HeadlessIntercept,
			&i.GraphqlConfig,
			&i.RestConfig,
			&i.SitemapConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScraperSourcesByPlace = `-- name: ListScraperSourcesByPlace :many
SELECT s.id, s.name, s.url, s.urls, s.tier, s.schedule, s.trust_level, s.license, s.enabled,
       s.max_pages, s.selectors, s.notes, s.event_url_pattern, s.skip_multi_session_check,
       s.multi_session_duration_threshold, s.follow_event_urls, s.timezone,
       s.last_scraped_at, s.created_at, s.updated_at,
       s.headless_wait_selector, s.headless_wait_timeout_ms, s.headless_pagination_btn,
       s.headless_headers, s.headless_rate_limit_ms,
       s.headless_wait_network_idle, s.headless_undetected, s.headless_iframe, s.headless_intercept,
       s.graphql_config, s.rest_config, s.sitemap_config
  FROM scraper_sources s
  JOIN place_scraper_sources l ON l.scraper_source_id = s.id
 WHERE l.place_id = $1
 ORDER BY s.name ASC
`

type ListScraperSourcesByPlaceRow struct {
	ID                            int64              `json:"id"`
	Name                          string             `json:"name"`
	Url                           string             `json:"url"`
	Urls                          []string           `json:"urls"`
	Tier                          int32              `json:"tier"`
	Schedule                      string             `json:"schedule"`
	TrustLevel                    int32              `json:"trust_level"`
	License                       string             `json:"license"`
	Enabled                       bool               `json:"enabled"`
	MaxPages                      int32              `json:"max_pages"`
	Selectors                     []byte             `json:"selectors"`
	Notes                         pgtype.Text        `json:"notes"`
	EventUrlPattern               string             `json:"event_url_pattern"`
	SkipMultiSessionCheck         bool               `json:"skip_multi_session_check"`
	MultiSessionDurationThreshold string             `json:"multi_session_duration_threshold"`
	FollowEventUrls               bool               `json:"follow_event_urls"`
	Timezone                      string             `json:"timezone"`
	LastScrapedAt                 pgtype.Timestamptz `json:"last_scraped_at"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	HeadlessWaitSelector          pgtype.Text        `json:"headless_wait_selector"`
	HeadlessWaitTimeoutMs         int32              `json:"headless_wait_timeout_ms"`
	HeadlessPaginationBtn         pgtype.Text        `json:"headless_pagination_btn"`
	HeadlessHeaders               []byte             `json:"headless_headers"`
	HeadlessRateLimitMs           int32              `json:"headless_rate_limit_ms"`
	HeadlessWaitNetworkIdle       bool               `json:"headless_wait_network_idle"`
	HeadlessUndetected            bool               `json:"headless_undetected"`
	HeadlessIframe                []byte             `json:"headless_iframe"`
	HeadlessIntercept             []byte             `json:"headless_intercept"`
	GraphqlConfig                 []byte             `json:"graphql_config"`
	RestConfig                    []byte             `json:"rest_config"`
	SitemapConfig                 []byte             `json:"sitemap_config"`
}

// List all scraper sources linked to a given place.
func (q *Queries) ListScraperSourcesByPlace(ctx context.Context, placeID pgtype.UUID) ([]ListScraperSourcesByPlaceRow, error) {
	rows, err := q.db.Query(ctx, listScraperSourcesByPlace, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScraperSourcesByPlaceRow{}
	for rows.Next() {
		var i ListScraperSourcesByPlaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Urls,
			&i.Tier,
			&i.Schedule,
			&i.TrustLevel,
			&i.License,
			&i.Enabled,
			&i.MaxPages,
			&i.Selectors,
			&i.Notes,
			&i.EventUrlPattern,
			&i.SkipMultiSessionCheck,
			&i.MultiSessionDurationThreshold,
			&i.FollowEventUrls,
			&i.Timezone,
			&i.LastScrapedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HeadlessWaitSelector,
			&i.HeadlessWaitTimeoutMs,
			&i.HeadlessPaginationBtn,
			&i.HeadlessHeaders,
			&i.HeadlessRateLimitMs,
			&i.HeadlessWaitNetworkIdle,
			&i.HeadlessUndetected,
			&i.HeadlessIframe,
			&i.HeadlessIntercept,
			&i.GraphqlConfig,
			&i.RestConfig,
			&i.SitemapConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScraperSourcesWithLatestRun = `-- name: ListScraperSourcesWithLatestRun :many
SELECT
  s.id, s.name, s.url, s.urls, s.tier, s.schedule, s.trust_level, s.license, s.enabled,
  s.max_pages, s.selectors, s.notes, s.event_url_pattern, s.skip_multi_session_check,
  s.multi_session_duration_threshold, s.follow_event_urls, s.timezone,
  s.last_scraped_at, s.created_at, s.updated_at,
  s.headless_wait_selector, s.headless_wait_timeout_ms, s.headless_pagination_btn,
  s.headless_headers, s.headless_rate_limit_ms,
  s.headless_wait_network_idle, s.headless_undetected, s.headless_iframe, s.headless_intercept,
  s.graphql_config, s.rest_config, s.sitemap_config,
  r.started_at                        AS last_run_started_at,
  r.completed_at                      AS last_run_completed_at,
  COALESCE(r.status, '')              AS last_run_status,
  COALESCE(r.events_found, 0)         AS last_run_events_found,
  COALESCE(r.events_new, 0)           AS last_run_events_new,
  COALESCE(r.events_dup, 0)          AS last_run_events_dup,
  COALESCE(r.events_failed, 0)       AS last_run_events_failed,
  r.error_message                     AS last_run_error_message
FROM scraper_sources s
LEFT JOIN LATERAL (
  SELECT started_at, completed_at, status,
         events_found, events_new, events_dup, events_failed, error_message
    FROM scraper_runs
   WHERE source_name = s.name
   ORDER BY started_at DESC
   LIMIT 1
) r ON true
WHERE ($1::boolean IS NULL OR s.enabled = $1)
ORDER BY s.name ASC
`

type ListScraperSourcesWithLatestRunRow struct {
	ID                            int64              `json:"id"`
	Name                          string             `json:"name"`
	Url                           string             `json:"url"`
	Urls                          []string           `json:"urls"`
	Tier                          int32              `json:"tier"`
	Schedule                      string             `json:"schedule"`
	TrustLevel                    int32              `json:"trust_level"`
	License                       string             `json:"license"`
	Enabled                       bool               `json:"enabled"`
	MaxPages                      int32              `json:"max_pages"`
	Selectors                     []byte             `json:"selectors"`
	Notes                         pgtype.Text        `json:"notes"`
	EventUrlPattern               string             `json:"event_url_pattern"`
	SkipMultiSessionCheck         bool               `json:"skip_multi_session_check"`
	MultiSessionDurationThreshold string             `json:"multi_session_duration_threshold"`
	FollowEventUrls               bool               `json:"follow_event_urls"`
	Timezone                      string             `json:"timezone"`
	LastScrapedAt                 pgtype.Timestamptz `json:"last_scraped_at"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	HeadlessWaitSelector          pgtype.Text        `json:"headless_wait_selector"`
	HeadlessWaitTimeoutMs         int32              `json:"headless_wait_timeout_ms"`
	HeadlessPaginationBtn         pgtype.Text        `json:"headless_pagination_btn"`
	HeadlessHeaders               []byte             `json:"headless_headers"`
	HeadlessRateLimitMs           int32              `json:"headless_rate_limit_ms"`
	HeadlessWaitNetworkIdle       bool               `json:"headless_wait_network_idle"`
	HeadlessUndetected            bool               `json:"headless_undetected"`
	HeadlessIframe                []byte             `json:"headless_iframe"`
	HeadlessIntercept             []byte             `json:"headless_intercept"`
	GraphqlConfig                 []byte             `json:"graphql_config"`
	RestConfig                    []byte             `json:"rest_config"`
	SitemapConfig                 []byte             `json:"sitemap_config"`
	LastRunStartedAt              pgtype.Timestamptz `json:"last_run_started_at"`
	LastRunCompletedAt            pgtype.Timestamptz `json:"last_run_completed_at"`
	LastRunStatus                 string             `json:"last_run_status"`
	LastRunEventsFound            int32              `json:"last_run_events_found"`
	LastRunEventsNew              int32              `json:"last_run_events_new"`
	LastRunEventsDup              int32              `json:"last_run_events_dup"`
	LastRunEventsFailed           int32              `json:"last_run_events_failed"`
	LastRunErrorMessage           pgtype.Text        `json:"last_run_error_message"`
}

// List all scraper sources with their most recent run stats embedded.
// last_run_started_at/completed_at/error_message are nullable (NULL when a source
// has never been run). status and event counts use COALESCE to return non-nullable
// defaults so SQLc generates simple string/int32 types for those columns.
func (q *Queries) ListScraperSourcesWithLatestRun(ctx context.Context, enabled pgtype.Bool) ([]ListScraperSourcesWithLatestRunRow, error) {
	rows, err := q.db.Query(ctx, listScraperSourcesWithLatestRun, enabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScraperSourcesWithLatestRunRow{}
	for rows.Next() {
		var i ListScraperSourcesWithLatestRunRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Urls,
			&i.Tier,
			&i.Schedule,
			&i.TrustLevel,
			&i.License,
			&i.Enabled,
			&i.MaxPages,
			&i.Selectors,
			&i.Notes,
			&i.EventUrlPattern,
			&i.SkipMultiSessionCheck,
			&i.MultiSessionDurationThreshold,
			&i.FollowEventUrls,
			&i.Timezone,
			&i.LastScrapedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HeadlessWaitSelector,
			&i.HeadlessWaitTimeoutMs,
			&i.HeadlessPaginationBtn,
			&i.HeadlessHeaders,
			&i.HeadlessRateLimitMs,
			&i.HeadlessWaitNetworkIdle,
			&i.HeadlessUndetected,
			&i.HeadlessIframe,
			&i.HeadlessIntercept,
			&i.GraphqlConfig,
			&i.RestConfig,
			&i.SitemapConfig,
			&i.LastRunStartedAt,
			&i.LastRunCompletedAt,
			&i.LastRunStatus,
			&i.LastRunEventsFound,
			&i.LastRunEventsNew,
			&i.LastRunEventsDup,
			&i.LastRunEventsFailed,
			&i.LastRunErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkOrgScraperSource = `-- name: UnlinkOrgScraperSource :exec
DELETE FROM org_scraper_sources
 WHERE organization_id   = $1
   AND scraper_source_id = $2
`

type UnlinkOrgScraperSourceParams struct {
	OrganizationID  pgtype.UUID `json:"organization_id"`
	ScraperSourceID int64       `json:"scraper_source_id"`
}

// Remove an organization↔scraper source association.
func (q *Queries) UnlinkOrgScraperSource(ctx context.Context, arg UnlinkOrgScraperSourceParams) error {
	_, err := q.db.Exec(ctx, unlinkOrgScraperSource, arg.OrganizationID, arg.ScraperSourceID)
	return err
}

const unlinkPlaceScraperSource = `-- name: UnlinkPlaceScraperSource :exec
DELETE FROM place_scraper_sources
 WHERE place_id           = $1
   AND scraper_source_id  = $2
`

type UnlinkPlaceScraperSourceParams struct {
	PlaceID         pgtype.UUID `json:"place_id"`
	ScraperSourceID int64       `json:"scraper_source_id"`
}

// Remove a place↔scraper source association.
func (q *Queries) UnlinkPlaceScraperSource(ctx context.Context, arg UnlinkPlaceScraperSourceParams) error {
	_, err := q.db.Exec(ctx, unlinkPlaceScraperSource, arg.PlaceID, arg.ScraperSourceID)
	return err
}

const updateScraperSourceLastScraped = `-- name: UpdateScraperSourceLastScraped :exec
UPDATE scraper_sources
   SET last_scraped_at = NOW(),
       updated_at      = NOW()
 WHERE name = $1
`

// Update last_scraped_at timestamp after a successful scrape run.
func (q *Queries) UpdateScraperSourceLastScraped(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, updateScraperSourceLastScraped, name)
	return err
}

const upsertScraperSource = `-- name: UpsertScraperSource :one

INSERT INTO scraper_sources (
  name, url, urls, tier, schedule, trust_level, license, enabled,
  max_pages, selectors, notes, event_url_pattern, skip_multi_session_check,
  multi_session_duration_threshold, follow_event_urls, timezone,
  last_scraped_at,
  headless_wait_selector, headless_wait_timeout_ms, headless_pagination_btn,
  headless_headers, headless_rate_limit_ms,
  headless_wait_network_idle, headless_undetected, headless_iframe, headless_intercept,
  graphql_config,
  rest_config,
  sitemap_config,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  $27,
  $28,
  $29,
  NOW()
)
ON CONFLICT (name) DO UPDATE SET
  url                      = EXCLUDED.url,
  urls                     = EXCLUDED.urls,
  tier                     = EXCLUDED.tier,
  schedule                 = EXCLUDED.schedule,
  trust_level              = EXCLUDED.trust_level,
  license                  = EXCLUDED.license,
  enabled                  = EXCLUDED.enabled,
  max_pages                = EXCLUDED.max_pages,
  selectors                = EXCLUDED.selectors,
  notes                    = EXCLUDED.notes,
  event_url_pattern        = EXCLUDED.event_url_pattern,
  skip_multi_session_check = EXCLUDED.skip_multi_session_check,
  multi_session_duration_threshold = EXCLUDED.multi_session_duration_threshold,
  follow_event_urls        = EXCLUDED.follow_event_urls,
  timezone                 = EXCLUDED.timezone,
  last_scraped_at          = COALESCE(EXCLUDED.last_scraped_at, scraper_sources.last_scraped_at),
  headless_wait_selector   = EXCLUDED.headless_wait_selector,
  headless_wait_timeout_ms = EXCLUDED.headless_wait_timeout_ms,
  headless_pagination_btn  = EXCLUDED.headless_pagination_btn,
  headless_headers         = EXCLUDED.headless_headers,
  headless_rate_limit_ms   = EXCLUDED.headless_rate_limit_ms,
  headless_wait_network_idle = EXCLUDED.headless_wait_network_idle,
  headless_undetected      = EXCLUDED.headless_undetected,
  headless_iframe          = EXCLUDED.headless_iframe,
  headless_intercept       = EXCLUDED.headless_intercept,
  graphql_config           = EXCLUDED.graphql_config,
  rest_config              = EXCLUDED.rest_config,
  sitemap_config           = EXCLUDED.sitemap_config,
  updated_at               = NOW()
RETURNING id, name, url, urls, tier, schedule, trust_level, license, enabled,
          max_pages, selectors, notes, event_url_pattern, skip_multi_session_check,
          multi_session_duration_threshold, follow_event_urls, timezone,
          last_scraped_at, created_at, updated_at,
          headless_wait_selector, headless_wait_timeout_ms, headless_pagination_btn,
          headless_headers, headless_rate_limit_ms,
          headless_wait_network_idle, headless_undetected, headless_iframe, headless_intercept,
          graphql_config, rest_config, sitemap_config
`

type UpsertScraperSourceParams struct {
	Name                          string             `json:"name"`
	Url                           string             `json:"url"`
	Urls                          []string           `json:"urls"`
	Tier                          int32              `json:"tier"`
	Schedule                      string             `json:"schedule"`
	TrustLevel                    int32              `json:"trust_level"`
	License                       string             `json:"license"`
	Enabled                       bool               `json:"enabled"`
	MaxPages                      int32              `json:"max_pages"`
	Selectors                     []byte             `json:"selectors"`
	Notes                         pgtype.Text        `json:"notes"`
	EventUrlPattern               string             `json:"event_url_pattern"`
	SkipMultiSessionCheck         bool               `json:"skip_multi_session_check"`
	MultiSessionDurationThreshold string             `json:"multi_session_duration_threshold"`
	FollowEventUrls               bool               `json:"follow_event_urls"`
	Timezone                      string             `json:"timezone"`
	LastScrapedAt                 pgtype.Timestamptz `json:"last_scraped_at"`
	HeadlessWaitSelector          pgtype.Text        `json:"headless_wait_selector"`
	HeadlessWaitTimeoutMs         int32              `json:"headless_wait_timeout_ms"`
	HeadlessPaginationBtn         pgtype.Text        `json:"headless_pagination_btn"`
	HeadlessHeaders               []byte             `json:"headless_headers"`
	HeadlessRateLimitMs           int32              `json:"headless_rate_limit_ms"`
	HeadlessWaitNetworkIdle       bool               `json:"headless_wait_network_idle"`
	HeadlessUndetected            bool               `json:"headless_undetected"`
	HeadlessIframe                []byte             `json:"headless_iframe"`
	HeadlessIntercept             []byte             `json:"headless_intercept"`
	GraphqlConfig                 []byte             `json:"graphql_config"`
	RestConfig                    []byte             `json:"rest_config"`
	SitemapConfig                 []byte             `json:"sitemap_config"`
}

type UpsertScraperSourceRow struct {
	ID                            int64              `json:"id"`
	Name                          string             `json:"name"`
	Url                           string             `json:"url"`
	Urls                          []string           `json:"urls"`
	Tier                          int32              `json:"tier"`
	Schedule                      string             `json:"schedule"`
	TrustLevel                    int32              `json:"trust_level"`
	License                       string             `json:"license"`
	Enabled                       bool               `json:"enabled"`
	MaxPages                      int32              `json:"max_pages"`
	Selectors                     []byte             `json:"selectors"`
	Notes                         pgtype.Text        `json:"notes"`
	EventUrlPattern               string             `json:"event_url_pattern"`
	SkipMultiSessionCheck         bool               `json:"skip_multi_session_check"`
	MultiSessionDurationThreshold string             `json:"multi_session_duration_threshold"`
	FollowEventUrls               bool               `json:"follow_event_urls"`
	Timezone                      string             `json:"timezone"`
	LastScrapedAt                 pgtype.Timestamptz `json:"last_scraped_at"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	HeadlessWaitSelector          pgtype.Text        `json:"headless_wait_selector"`
	HeadlessWaitTimeoutMs         int32              `json:"headless_wait_timeout_ms"`
	HeadlessPaginationBtn         pgtype.Text        `json:"headless_pagination_btn"`
	HeadlessHeaders               []byte             `json:"headless_headers"`
	HeadlessRateLimitMs           int32              `json:"headless_rate_limit_ms"`
	HeadlessWaitNetworkIdle       bool               `json:"headless_wait_network_idle"`
	HeadlessUndetected            bool               `json:"headless_undetected"`
	HeadlessIframe                []byte             `json:"headless_iframe"`
	HeadlessIntercept             []byte             `json:"headless_intercept"`
	GraphqlConfig                 []byte             `json:"graphql_config"`
	RestConfig                    []byte             `json:"rest_config"`
	SitemapConfig                 []byte             `json:"sitemap_config"`
}

// SQLc queries for scraper_sources and linkage tables.
// Insert or update a scraper source by name (used by 'server scrape sync').
func (q *Queries) UpsertScraperSource(ctx context.Context, arg UpsertScraperSourceParams) (UpsertScraperSourceRow, error) {
	row := q.db.QueryRow(ctx, upsertScraperSource,
		arg.Name,
		arg.Url,
		arg.Urls,
		arg.Tier,
		arg.Schedule,
		arg.TrustLevel,
		arg.License,
		arg.Enabled,
		arg.MaxPages,
		arg.Selectors,
		arg.Notes,
		arg.EventUrlPattern,
		arg.SkipMultiSessionCheck,
		arg.MultiSessionDurationThreshold,
		arg.FollowEventUrls,
		arg.Timezone,
		arg.LastScrapedAt,
		arg.HeadlessWaitSelector,
		arg.HeadlessWaitTimeoutMs,
		arg.HeadlessPaginationBtn,
		arg.HeadlessHeaders,
		arg.HeadlessRateLimitMs,
		arg.HeadlessWaitNetworkIdle,
		arg.HeadlessUndetected,
		arg.HeadlessIframe,
		arg.HeadlessIntercept,
		arg.GraphqlConfig,
		arg.RestConfig,
		arg.SitemapConfig,
	)
	var i UpsertScraperSourceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Urls,
		&i.Tier,
		&i.Schedule,
		&i.TrustLevel,
		&i.License,
		&i.Enabled,
		&i.MaxPages,
		&i.Selectors,
		&i.Notes,
		&i.EventUrlPattern,
		&i.SkipMultiSessionCheck,
		&i.MultiSessionDurationThreshold,
		&i.FollowEventUrls,
		&i.Timezone,
		&i.LastScrapedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadlessWaitSelector,
		&i.HeadlessWaitTimeoutMs,
		&i.HeadlessPaginationBtn,
		&i.HeadlessHeaders,
		&i.HeadlessRateLimitMs,
		&i.HeadlessWaitNetworkIdle,
		&i.HeadlessUndetected,
		&i.HeadlessIframe,
		&i.HeadlessIntercept,
		&i.GraphqlConfig,
		&i.RestConfig,
		&i.SitemapConfig,
	)
	return i, err
}
