#!/usr/bin/env bash
#
# test_webfiles_e2e.sh - End-to-end test for webfiles automation
#
# Simulates the complete deployment flow and verifies webfiles are generated
# correctly for each environment.

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Test counters
TESTS_PASSED=0
TESTS_FAILED=0

log() {
    local level="$1"
    shift
    case "$level" in
        ERROR)   echo -e "${RED}[ERROR]${NC} $*" >&2 ;;
        PASS)    echo -e "${GREEN}[PASS]${NC} $*" ;;
        FAIL)    echo -e "${RED}[FAIL]${NC} $*" ;;
        INFO)    echo -e "${BLUE}[INFO]${NC} $*" ;;
    esac
}

test_webfiles_command() {
    local env="$1"
    local expected_domain="$2"
    
    log "INFO" "Testing: server webfiles --domain ${expected_domain}"
    
    # Create temp directory for this test
    local temp_dir=$(mktemp -d)
    
    # Generate webfiles
    if ! "${PROJECT_ROOT}/server" webfiles --domain "${expected_domain}" --output "${temp_dir}" >/dev/null 2>&1; then
        log "FAIL" "${env}: webfiles command failed"
        rm -rf "${temp_dir}"
        ((TESTS_FAILED++))
        return 1
    fi
    
    # Verify robots.txt
    if [[ ! -f "${temp_dir}/robots.txt" ]]; then
        log "FAIL" "${env}: robots.txt not generated"
        rm -rf "${temp_dir}"
        ((TESTS_FAILED++))
        return 1
    fi
    
    if ! grep -q "Sitemap: https://${expected_domain}/sitemap.xml" "${temp_dir}/robots.txt"; then
        log "FAIL" "${env}: robots.txt has wrong sitemap URL"
        grep "Sitemap:" "${temp_dir}/robots.txt" >&2
        rm -rf "${temp_dir}"
        ((TESTS_FAILED++))
        return 1
    fi
    
    # Verify sitemap.xml
    if [[ ! -f "${temp_dir}/sitemap.xml" ]]; then
        log "FAIL" "${env}: sitemap.xml not generated"
        rm -rf "${temp_dir}"
        ((TESTS_FAILED++))
        return 1
    fi
    
    if ! grep -q "<loc>https://${expected_domain}/" "${temp_dir}/sitemap.xml"; then
        log "FAIL" "${env}: sitemap.xml has wrong domain"
        grep "<loc>" "${temp_dir}/sitemap.xml" | head -3 >&2
        rm -rf "${temp_dir}"
        ((TESTS_FAILED++))
        return 1
    fi
    
    # Verify lastmod tags present
    if ! grep -q "<lastmod>" "${temp_dir}/sitemap.xml"; then
        log "FAIL" "${env}: sitemap.xml missing lastmod tags"
        rm -rf "${temp_dir}"
        ((TESTS_FAILED++))
        return 1
    fi
    
    # Count URLs in sitemap
    local url_count=$(grep -c "<loc>" "${temp_dir}/sitemap.xml")
    if [[ $url_count -lt 5 ]]; then
        log "FAIL" "${env}: sitemap.xml has too few URLs (${url_count})"
        rm -rf "${temp_dir}"
        ((TESTS_FAILED++))
        return 1
    fi
    
    log "PASS" "${env}: webfiles generated correctly (${url_count} URLs)"
    rm -rf "${temp_dir}"
    ((TESTS_PASSED++))
    return 0
}

test_deploy_script_integration() {
    local env="$1"
    local expected_domain="$2"
    
    log "INFO" "Testing: generate_web_files ${env}"
    
    # Create temp directory
    local temp_dir=$(mktemp -d)
    
    # Source deploy.sh to get generate_web_files function
    cd "${PROJECT_ROOT}"
    PROJECT_ROOT="${PROJECT_ROOT}" bash -c "
        source ./deploy/scripts/deploy.sh
        
        # Override log function for testing
        log() { echo \"[\$1] \$*\" >/dev/null; }
        
        # Test generate_web_files
        if generate_web_files '${env}'; then
            exit 0
        else
            exit 1
        fi
    " >/dev/null 2>&1
    
    if [[ $? -ne 0 ]]; then
        log "FAIL" "${env}: generate_web_files failed"
        rm -rf "${temp_dir}"
        ((TESTS_FAILED++))
        return 1
    fi
    
    # Verify files were generated in PROJECT_ROOT/web
    if [[ ! -f "${PROJECT_ROOT}/web/robots.txt" ]]; then
        log "FAIL" "${env}: robots.txt not generated by deploy script"
        rm -rf "${temp_dir}"
        ((TESTS_FAILED++))
        return 1
    fi
    
    if ! grep -q "Sitemap: https://${expected_domain}/sitemap.xml" "${PROJECT_ROOT}/web/robots.txt"; then
        log "FAIL" "${env}: deploy script generated wrong domain"
        grep "Sitemap:" "${PROJECT_ROOT}/web/robots.txt" >&2
        rm -rf "${temp_dir}"
        ((TESTS_FAILED++))
        return 1
    fi
    
    log "PASS" "${env}: generate_web_files works correctly"
    rm -rf "${temp_dir}"
    ((TESTS_PASSED++))
    return 0
}

test_embedded_content() {
    local expected_domain="$1"
    
    log "INFO" "Testing: embedded content in binary"
    
    # Check if binary exists
    if [[ ! -f "${PROJECT_ROOT}/bin/togather-server" ]]; then
        log "FAIL" "Binary not found at bin/togather-server"
        ((TESTS_FAILED++))
        return 1
    fi
    
    # Check if binary contains the expected domain
    if strings "${PROJECT_ROOT}/bin/togather-server" | grep -q "${expected_domain}"; then
        log "PASS" "Binary contains ${expected_domain}"
        ((TESTS_PASSED++))
        return 0
    else
        log "FAIL" "Binary does not contain ${expected_domain}"
        ((TESTS_FAILED++))
        return 1
    fi
}

main() {
    log "INFO" "Starting webfiles automation E2E tests"
    echo ""
    
    # Check if server binary exists
    if [[ ! -f "${PROJECT_ROOT}/server" ]]; then
        log "ERROR" "Server binary not found. Run 'make build' first."
        exit 1
    fi
    
    # Test 1: Production environment
    echo "=== Test 1: Production Environment ==="
    test_webfiles_command "production" "togather.foundation"
    echo ""
    
    # Test 2: Staging environment
    echo "=== Test 2: Staging Environment ==="
    test_webfiles_command "staging" "staging.toronto.togather.foundation"
    echo ""
    
    # Test 3: Development environment
    echo "=== Test 3: Development Environment ==="
    test_webfiles_command "development" "localhost:8080"
    echo ""
    
    # Test 4: Deploy script integration - production
    echo "=== Test 4: Deploy Script Integration - Production ==="
    test_deploy_script_integration "production" "togather.foundation"
    echo ""
    
    # Test 5: Deploy script integration - staging
    echo "=== Test 5: Deploy Script Integration - Staging ==="
    test_deploy_script_integration "staging" "staging.toronto.togather.foundation"
    echo ""
    
    # Test 6: Verify binary contains latest domain (from last test)
    echo "=== Test 6: Binary Embedded Content ==="
    test_embedded_content "staging.toronto.togather.foundation"
    echo ""
    
    # Summary
    echo "========================================"
    log "INFO" "Test Summary"
    echo "========================================"
    log "INFO" "Tests passed: ${TESTS_PASSED}"
    log "INFO" "Tests failed: ${TESTS_FAILED}"
    echo ""
    
    if [[ $TESTS_FAILED -eq 0 ]]; then
        log "PASS" "All E2E tests passed!"
        exit 0
    else
        log "ERROR" "${TESTS_FAILED} test(s) failed"
        exit 1
    fi
}

main "$@"
