regions:
  - Ontario
localities:
  - Toronto
  - Old Toronto
  - York
  - North York
  - Scarborough
  - Etobicoke
  - Mississauga
  - Brampton
  - Markham
  - Richmond Hill
  - Vaughan
  - Pickering
  - Ajax
  - Whitby
  - Oshawa
